export const cities = [
  {
    id: 1,
    name: 'اسکو',
    value: 'اسکو',
    province_id: 1,
  },
  {
    id: 2,
    name: 'اهر',
    value: 'اهر',
    province_id: 1,
  },
  {
    id: 3,
    name: 'ایلخچی',
    value: 'ایلخچی',
    province_id: 1,
  },
  {
    id: 4,
    name: 'آبش احمد',
    value: 'آبش-احمد',
    province_id: 1,
  },
  {
    id: 5,
    name: 'آذرشهر',
    value: 'آذرشهر',
    province_id: 1,
  },
  {
    id: 6,
    name: 'آقکند',
    value: 'آقکند',
    province_id: 1,
  },
  {
    id: 7,
    name: 'باسمنج',
    value: 'باسمنج',
    province_id: 1,
  },
  {
    id: 8,
    name: 'بخشایش',
    value: 'بخشایش',
    province_id: 1,
  },
  {
    id: 9,
    name: 'بستان آباد',
    value: 'بستان-آباد',
    province_id: 1,
  },
  {
    id: 10,
    name: 'بناب',
    value: 'بناب',
    province_id: 1,
  },
  {
    id: 11,
    name: 'بناب جدید',
    value: 'بناب-جدید',
    province_id: 1,
  },
  {
    id: 12,
    name: 'تبریز',
    value: 'تبریز',
    province_id: 1,
  },
  {
    id: 13,
    name: 'ترک',
    value: 'ترک',
    province_id: 1,
  },
  {
    id: 14,
    name: 'ترکمانچای',
    value: 'ترکمانچای',
    province_id: 1,
  },
  {
    id: 15,
    name: 'تسوج',
    value: 'تسوج',
    province_id: 1,
  },
  {
    id: 16,
    name: 'تیکمه داش',
    value: 'تیکمه-داش',
    province_id: 1,
  },
  {
    id: 17,
    name: 'جلفا',
    value: 'جلفا',
    province_id: 1,
  },
  {
    id: 18,
    name: 'خاروانا',
    value: 'خاروانا',
    province_id: 1,
  },
  {
    id: 19,
    name: 'خامنه',
    value: 'خامنه',
    province_id: 1,
  },
  {
    id: 20,
    name: 'خراجو',
    value: 'خراجو',
    province_id: 1,
  },
  {
    id: 21,
    name: 'خسروشهر',
    value: 'خسروشهر',
    province_id: 1,
  },
  {
    id: 22,
    name: 'خضرلو',
    value: 'خضرلو',
    province_id: 1,
  },
  {
    id: 23,
    name: 'خمارلو',
    value: 'خمارلو',
    province_id: 1,
  },
  {
    id: 24,
    name: 'خواجه',
    value: 'خواجه',
    province_id: 1,
  },
  {
    id: 25,
    name: 'دوزدوزان',
    value: 'دوزدوزان',
    province_id: 1,
  },
  {
    id: 26,
    name: 'زرنق',
    value: 'زرنق',
    province_id: 1,
  },
  {
    id: 27,
    name: 'زنوز',
    value: 'زنوز',
    province_id: 1,
  },
  {
    id: 28,
    name: 'سراب',
    value: 'سراب',
    province_id: 1,
  },
  {
    id: 29,
    name: 'سردرود',
    value: 'سردرود',
    province_id: 1,
  },
  {
    id: 30,
    name: 'سهند',
    value: 'سهند',
    province_id: 1,
  },
  {
    id: 31,
    name: 'سیس',
    value: 'سیس',
    province_id: 1,
  },
  {
    id: 32,
    name: 'سیه رود',
    value: 'سیه-رود',
    province_id: 1,
  },
  {
    id: 33,
    name: 'شبستر',
    value: 'شبستر',
    province_id: 1,
  },
  {
    id: 34,
    name: 'شربیان',
    value: 'شربیان',
    province_id: 1,
  },
  {
    id: 35,
    name: 'شرفخانه',
    value: 'شرفخانه',
    province_id: 1,
  },
  {
    id: 36,
    name: 'شندآباد',
    value: 'شندآباد',
    province_id: 1,
  },
  {
    id: 37,
    name: 'صوفیان',
    value: 'صوفیان',
    province_id: 1,
  },
  {
    id: 38,
    name: 'عجب شیر',
    value: 'عجب-شیر',
    province_id: 1,
  },
  {
    id: 39,
    name: 'قره آغاج',
    value: 'قره-آغاج',
    province_id: 1,
  },
  {
    id: 40,
    name: 'کشکسرای',
    value: 'کشکسرای',
    province_id: 1,
  },
  {
    id: 41,
    name: 'کلوانق',
    value: 'کلوانق',
    province_id: 1,
  },
  {
    id: 42,
    name: 'کلیبر',
    value: 'کلیبر',
    province_id: 1,
  },
  {
    id: 43,
    name: 'کوزه کنان',
    value: 'کوزه-کنان',
    province_id: 1,
  },
  {
    id: 44,
    name: 'گوگان',
    value: 'گوگان',
    province_id: 1,
  },
  {
    id: 45,
    name: 'لیلان',
    value: 'لیلان',
    province_id: 1,
  },
  {
    id: 46,
    name: 'مراغه',
    value: 'مراغه',
    province_id: 1,
  },
  {
    id: 47,
    name: 'مرند',
    value: 'مرند',
    province_id: 1,
  },
  {
    id: 48,
    name: 'ملکان',
    value: 'ملکان',
    province_id: 1,
  },
  {
    id: 49,
    name: 'ملک کیان',
    value: 'ملک-کیان',
    province_id: 1,
  },
  {
    id: 50,
    name: 'ممقان',
    value: 'ممقان',
    province_id: 1,
  },
  {
    id: 51,
    name: 'مهربان',
    value: 'مهربان',
    province_id: 1,
  },
  {
    id: 52,
    name: 'میانه',
    value: 'میانه',
    province_id: 1,
  },
  {
    id: 53,
    name: 'نظرکهریزی',
    value: 'نظرکهریزی',
    province_id: 1,
  },
  {
    id: 54,
    name: 'هادی شهر',
    value: 'هادی-شهر',
    province_id: 1,
  },
  {
    id: 55,
    name: 'هرگلان',
    value: 'هرگلان',
    province_id: 1,
  },
  {
    id: 56,
    name: 'هریس',
    value: 'هریس',
    province_id: 1,
  },
  {
    id: 57,
    name: 'هشترود',
    value: 'هشترود',
    province_id: 1,
  },
  {
    id: 58,
    name: 'هوراند',
    value: 'هوراند',
    province_id: 1,
  },
  {
    id: 59,
    name: 'وایقان',
    value: 'وایقان',
    province_id: 1,
  },
  {
    id: 60,
    name: 'ورزقان',
    value: 'ورزقان',
    province_id: 1,
  },
  {
    id: 61,
    name: 'یامچی',
    value: 'یامچی',
    province_id: 1,
  },
  {
    id: 62,
    name: 'ارومیه',
    value: 'ارومیه',
    province_id: 2,
  },
  {
    id: 63,
    name: 'اشنویه',
    value: 'اشنویه',
    province_id: 2,
  },
  {
    id: 64,
    name: 'ایواوغلی',
    value: 'ایواوغلی',
    province_id: 2,
  },
  {
    id: 65,
    name: 'آواجیق',
    value: 'آواجیق',
    province_id: 2,
  },
  {
    id: 66,
    name: 'باروق',
    value: 'باروق',
    province_id: 2,
  },
  {
    id: 67,
    name: 'بازرگان',
    value: 'بازرگان',
    province_id: 2,
  },
  {
    id: 68,
    name: 'بوکان',
    value: 'بوکان',
    province_id: 2,
  },
  {
    id: 69,
    name: 'پلدشت',
    value: 'پلدشت',
    province_id: 2,
  },
  {
    id: 70,
    name: 'پیرانشهر',
    value: 'پیرانشهر',
    province_id: 2,
  },
  {
    id: 71,
    name: 'تازه شهر',
    value: 'تازه-شهر',
    province_id: 2,
  },
  {
    id: 72,
    name: 'تکاب',
    value: 'تکاب',
    province_id: 2,
  },
  {
    id: 73,
    name: 'چهاربرج',
    value: 'چهاربرج',
    province_id: 2,
  },
  {
    id: 74,
    name: 'خوی',
    value: 'خوی',
    province_id: 2,
  },
  {
    id: 75,
    name: 'دیزج دیز',
    value: 'دیزج-دیز',
    province_id: 2,
  },
  {
    id: 76,
    name: 'ربط',
    value: 'ربط',
    province_id: 2,
  },
  {
    id: 77,
    name: 'سردشت',
    value: 'آذربایجان-غربی-سردشت',
    province_id: 2,
  },
  {
    id: 78,
    name: 'سرو',
    value: 'سرو',
    province_id: 2,
  },
  {
    id: 79,
    name: 'سلماس',
    value: 'سلماس',
    province_id: 2,
  },
  {
    id: 80,
    name: 'سیلوانه',
    value: 'سیلوانه',
    province_id: 2,
  },
  {
    id: 81,
    name: 'سیمینه',
    value: 'سیمینه',
    province_id: 2,
  },
  {
    id: 82,
    name: 'سیه چشمه',
    value: 'سیه-چشمه',
    province_id: 2,
  },
  {
    id: 83,
    name: 'شاهین دژ',
    value: 'شاهین-دژ',
    province_id: 2,
  },
  {
    id: 84,
    name: 'شوط',
    value: 'شوط',
    province_id: 2,
  },
  {
    id: 85,
    name: 'فیرورق',
    value: 'فیرورق',
    province_id: 2,
  },
  {
    id: 86,
    name: 'قره ضیاءالدین',
    value: 'قره-ضیاءالدین',
    province_id: 2,
  },
  {
    id: 87,
    name: 'قطور',
    value: 'قطور',
    province_id: 2,
  },
  {
    id: 88,
    name: 'قوشچی',
    value: 'قوشچی',
    province_id: 2,
  },
  {
    id: 89,
    name: 'کشاورز',
    value: 'کشاورز',
    province_id: 2,
  },
  {
    id: 90,
    name: 'گردکشانه',
    value: 'گردکشانه',
    province_id: 2,
  },
  {
    id: 91,
    name: 'ماکو',
    value: 'ماکو',
    province_id: 2,
  },
  {
    id: 92,
    name: 'محمدیار',
    value: 'محمدیار',
    province_id: 2,
  },
  {
    id: 93,
    name: 'محمودآباد',
    value: 'آذربایجان-غربی-محمودآباد',
    province_id: 2,
  },
  {
    id: 94,
    name: 'مهاباد',
    value: 'آذربایجان-غربی-مهاباد',
    province_id: 2,
  },
  {
    id: 95,
    name: 'میاندوآب',
    value: 'میاندوآب',
    province_id: 2,
  },
  {
    id: 96,
    name: 'میرآباد',
    value: 'میرآباد',
    province_id: 2,
  },
  {
    id: 97,
    name: 'نالوس',
    value: 'نالوس',
    province_id: 2,
  },
  {
    id: 98,
    name: 'نقده',
    value: 'نقده',
    province_id: 2,
  },
  {
    id: 99,
    name: 'نوشین',
    value: 'نوشین',
    province_id: 2,
  },
  {
    id: 100,
    name: 'اردبیل',
    value: 'اردبیل',
    province_id: 3,
  },
  {
    id: 101,
    name: 'اصلاندوز',
    value: 'اصلاندوز',
    province_id: 3,
  },
  {
    id: 102,
    name: 'آبی بیگلو',
    value: 'آبی-بیگلو',
    province_id: 3,
  },
  {
    id: 103,
    name: 'بیله سوار',
    value: 'بیله-سوار',
    province_id: 3,
  },
  {
    id: 104,
    name: 'پارس آباد',
    value: 'پارس-آباد',
    province_id: 3,
  },
  {
    id: 105,
    name: 'تازه کند',
    value: 'تازه-کند',
    province_id: 3,
  },
  {
    id: 106,
    name: 'تازه کندانگوت',
    value: 'تازه-کندانگوت',
    province_id: 3,
  },
  {
    id: 107,
    name: 'جعفرآباد',
    value: 'جعفرآباد',
    province_id: 3,
  },
  {
    id: 108,
    name: 'خلخال',
    value: 'خلخال',
    province_id: 3,
  },
  {
    id: 109,
    name: 'رضی',
    value: 'رضی',
    province_id: 3,
  },
  {
    id: 110,
    name: 'سرعین',
    value: 'سرعین',
    province_id: 3,
  },
  {
    id: 111,
    name: 'عنبران',
    value: 'عنبران',
    province_id: 3,
  },
  {
    id: 112,
    name: 'فخرآباد',
    value: 'فخرآباد',
    province_id: 3,
  },
  {
    id: 113,
    name: 'کلور',
    value: 'کلور',
    province_id: 3,
  },
  {
    id: 114,
    name: 'کوراییم',
    value: 'کوراییم',
    province_id: 3,
  },
  {
    id: 115,
    name: 'گرمی',
    value: 'گرمی',
    province_id: 3,
  },
  {
    id: 116,
    name: 'گیوی',
    value: 'گیوی',
    province_id: 3,
  },
  {
    id: 117,
    name: 'لاهرود',
    value: 'لاهرود',
    province_id: 3,
  },
  {
    id: 118,
    name: 'مشگین شهر',
    value: 'مشگین-شهر',
    province_id: 3,
  },
  {
    id: 119,
    name: 'نمین',
    value: 'نمین',
    province_id: 3,
  },
  {
    id: 120,
    name: 'نیر',
    value: 'اردبیل-نیر',
    province_id: 3,
  },
  {
    id: 121,
    name: 'هشتجین',
    value: 'هشتجین',
    province_id: 3,
  },
  {
    id: 122,
    name: 'هیر',
    value: 'هیر',
    province_id: 3,
  },
  {
    id: 123,
    name: 'ابریشم',
    value: 'ابریشم',
    province_id: 4,
  },
  {
    id: 124,
    name: 'ابوزیدآباد',
    value: 'ابوزیدآباد',
    province_id: 4,
  },
  {
    id: 125,
    name: 'اردستان',
    value: 'اردستان',
    province_id: 4,
  },
  {
    id: 126,
    name: 'اژیه',
    value: 'اژیه',
    province_id: 4,
  },
  {
    id: 127,
    name: 'اصفهان',
    value: 'اصفهان',
    province_id: 4,
  },
  {
    id: 128,
    name: 'افوس',
    value: 'افوس',
    province_id: 4,
  },
  {
    id: 129,
    name: 'انارک',
    value: 'انارک',
    province_id: 4,
  },
  {
    id: 130,
    name: 'ایمانشهر',
    value: 'ایمانشهر',
    province_id: 4,
  },
  {
    id: 131,
    name: 'آران وبیدگل',
    value: 'آران-وبیدگل',
    province_id: 4,
  },
  {
    id: 132,
    name: 'بادرود',
    value: 'بادرود',
    province_id: 4,
  },
  {
    id: 133,
    name: 'باغ بهادران',
    value: 'باغ-بهادران',
    province_id: 4,
  },
  {
    id: 134,
    name: 'بافران',
    value: 'بافران',
    province_id: 4,
  },
  {
    id: 135,
    name: 'برزک',
    value: 'برزک',
    province_id: 4,
  },
  {
    id: 136,
    name: 'برف انبار',
    value: 'برف-انبار',
    province_id: 4,
  },
  {
    id: 137,
    name: 'بهاران شهر',
    value: 'بهاران-شهر',
    province_id: 4,
  },
  {
    id: 138,
    name: 'بهارستان',
    value: 'بهارستان',
    province_id: 4,
  },
  {
    id: 139,
    name: 'بوئین و میاندشت',
    value: 'بوئین-میاندشت',
    province_id: 4,
  },
  {
    id: 140,
    name: 'پیربکران',
    value: 'پیربکران',
    province_id: 4,
  },
  {
    id: 141,
    name: 'تودشک',
    value: 'تودشک',
    province_id: 4,
  },
  {
    id: 142,
    name: 'تیران',
    value: 'تیران',
    province_id: 4,
  },
  {
    id: 143,
    name: 'جندق',
    value: 'جندق',
    province_id: 4,
  },
  {
    id: 144,
    name: 'جوزدان',
    value: 'جوزدان',
    province_id: 4,
  },
  {
    id: 145,
    name: 'جوشقان و کامو',
    value: 'جوشقان-کامو',
    province_id: 4,
  },
  {
    id: 146,
    name: 'چادگان',
    value: 'چادگان',
    province_id: 4,
  },
  {
    id: 147,
    name: 'چرمهین',
    value: 'چرمهین',
    province_id: 4,
  },
  {
    id: 148,
    name: 'چمگردان',
    value: 'چمگردان',
    province_id: 4,
  },
  {
    id: 149,
    name: 'حبیب آباد',
    value: 'حبیب-آباد',
    province_id: 4,
  },
  {
    id: 150,
    name: 'حسن آباد',
    value: 'اصفهان-حسن-آباد',
    province_id: 4,
  },
  {
    id: 151,
    name: 'حنا',
    value: 'حنا',
    province_id: 4,
  },
  {
    id: 152,
    name: 'خالدآباد',
    value: 'خالدآباد',
    province_id: 4,
  },
  {
    id: 153,
    name: 'خمینی شهر',
    value: 'خمینی-شهر',
    province_id: 4,
  },
  {
    id: 154,
    name: 'خوانسار',
    value: 'خوانسار',
    province_id: 4,
  },
  {
    id: 155,
    name: 'خور',
    value: 'اصفهان-خور',
    province_id: 4,
  },
  {
    id: 157,
    name: 'خورزوق',
    value: 'خورزوق',
    province_id: 4,
  },
  {
    id: 158,
    name: 'داران',
    value: 'داران',
    province_id: 4,
  },
  {
    id: 159,
    name: 'دامنه',
    value: 'دامنه',
    province_id: 4,
  },
  {
    id: 160,
    name: 'درچه',
    value: 'درچه',
    province_id: 4,
  },
  {
    id: 161,
    name: 'دستگرد',
    value: 'دستگرد',
    province_id: 4,
  },
  {
    id: 162,
    name: 'دهاقان',
    value: 'دهاقان',
    province_id: 4,
  },
  {
    id: 163,
    name: 'دهق',
    value: 'دهق',
    province_id: 4,
  },
  {
    id: 164,
    name: 'دولت آباد',
    value: 'اصفهان-دولت-آباد',
    province_id: 4,
  },
  {
    id: 165,
    name: 'دیزیچه',
    value: 'دیزیچه',
    province_id: 4,
  },
  {
    id: 166,
    name: 'رزوه',
    value: 'رزوه',
    province_id: 4,
  },
  {
    id: 167,
    name: 'رضوانشهر',
    value: 'اصفهان-رضوانشهر',
    province_id: 4,
  },
  {
    id: 168,
    name: 'زاینده رود',
    value: 'زاینده-رود',
    province_id: 4,
  },
  {
    id: 169,
    name: 'زرین شهر',
    value: 'زرین-شهر',
    province_id: 4,
  },
  {
    id: 170,
    name: 'زواره',
    value: 'زواره',
    province_id: 4,
  },
  {
    id: 171,
    name: 'زیباشهر',
    value: 'زیباشهر',
    province_id: 4,
  },
  {
    id: 172,
    name: 'سده لنجان',
    value: 'سده-لنجان',
    province_id: 4,
  },
  {
    id: 173,
    name: 'سفیدشهر',
    value: 'سفیدشهر',
    province_id: 4,
  },
  {
    id: 174,
    name: 'سگزی',
    value: 'سگزی',
    province_id: 4,
  },
  {
    id: 175,
    name: 'سمیرم',
    value: 'سمیرم',
    province_id: 4,
  },
  {
    id: 176,
    name: 'شاهین شهر',
    value: 'شاهین-شهر',
    province_id: 4,
  },
  {
    id: 177,
    name: 'شهرضا',
    value: 'شهرضا',
    province_id: 4,
  },
  {
    id: 178,
    name: 'طالخونچه',
    value: 'طالخونچه',
    province_id: 4,
  },
  {
    id: 179,
    name: 'عسگران',
    value: 'عسگران',
    province_id: 4,
  },
  {
    id: 180,
    name: 'علویجه',
    value: 'علویجه',
    province_id: 4,
  },
  {
    id: 181,
    name: 'فرخی',
    value: 'فرخی',
    province_id: 4,
  },
  {
    id: 182,
    name: 'فریدونشهر',
    value: 'فریدونشهر',
    province_id: 4,
  },
  {
    id: 183,
    name: 'فلاورجان',
    value: 'فلاورجان',
    province_id: 4,
  },
  {
    id: 184,
    name: 'فولادشهر',
    value: 'فولادشهر',
    province_id: 4,
  },
  {
    id: 185,
    name: 'قمصر',
    value: 'قمصر',
    province_id: 4,
  },
  {
    id: 186,
    name: 'قهجاورستان',
    value: 'قهجاورستان',
    province_id: 4,
  },
  {
    id: 187,
    name: 'قهدریجان',
    value: 'قهدریجان',
    province_id: 4,
  },
  {
    id: 188,
    name: 'کاشان',
    value: 'کاشان',
    province_id: 4,
  },
  {
    id: 189,
    name: 'کرکوند',
    value: 'کرکوند',
    province_id: 4,
  },
  {
    id: 190,
    name: 'کلیشاد و سودرجان',
    value: 'کلیشاد-سودرجان',
    province_id: 4,
  },
  {
    id: 191,
    name: 'کمشچه',
    value: 'کمشچه',
    province_id: 4,
  },
  {
    id: 192,
    name: 'کمه',
    value: 'کمه',
    province_id: 4,
  },
  {
    id: 193,
    name: 'کهریزسنگ',
    value: 'کهریزسنگ',
    province_id: 4,
  },
  {
    id: 194,
    name: 'کوشک',
    value: 'کوشک',
    province_id: 4,
  },
  {
    id: 195,
    name: 'کوهپایه',
    value: 'کوهپایه',
    province_id: 4,
  },
  {
    id: 196,
    name: 'گرگاب',
    value: 'گرگاب',
    province_id: 4,
  },
  {
    id: 197,
    name: 'گزبرخوار',
    value: 'گزبرخوار',
    province_id: 4,
  },
  {
    id: 198,
    name: 'گلپایگان',
    value: 'گلپایگان',
    province_id: 4,
  },
  {
    id: 199,
    name: 'گلدشت',
    value: 'گلدشت',
    province_id: 4,
  },
  {
    id: 200,
    name: 'گلشهر',
    value: 'گلشهر',
    province_id: 4,
  },
  {
    id: 201,
    name: 'گوگد',
    value: 'گوگد',
    province_id: 4,
  },
  {
    id: 202,
    name: 'لای بید',
    value: 'لای-بید',
    province_id: 4,
  },
  {
    id: 203,
    name: 'مبارکه',
    value: 'مبارکه',
    province_id: 4,
  },
  {
    id: 204,
    name: 'مجلسی',
    value: 'مجلسی',
    province_id: 4,
  },
  {
    id: 205,
    name: 'محمدآباد',
    value: 'اصفهان-محمدآباد',
    province_id: 4,
  },
  {
    id: 206,
    name: 'مشکات',
    value: 'مشکات',
    province_id: 4,
  },
  {
    id: 207,
    name: 'منظریه',
    value: 'منظریه',
    province_id: 4,
  },
  {
    id: 208,
    name: 'مهاباد',
    value: 'اصفهان-مهاباد',
    province_id: 4,
  },
  {
    id: 209,
    name: 'میمه',
    value: 'اصفهان-میمه',
    province_id: 4,
  },
  {
    id: 210,
    name: 'نائین',
    value: 'نائین',
    province_id: 4,
  },
  {
    id: 211,
    name: 'نجف آباد',
    value: 'نجف-آباد',
    province_id: 4,
  },
  {
    id: 212,
    name: 'نصرآباد',
    value: 'اصفهان-نصرآباد',
    province_id: 4,
  },
  {
    id: 213,
    name: 'نطنز',
    value: 'نطنز',
    province_id: 4,
  },
  {
    id: 214,
    name: 'نوش آباد',
    value: 'نوش-آباد',
    province_id: 4,
  },
  {
    id: 215,
    name: 'نیاسر',
    value: 'نیاسر',
    province_id: 4,
  },
  {
    id: 216,
    name: 'نیک آباد',
    value: 'نیک-آباد',
    province_id: 4,
  },
  {
    id: 217,
    name: 'هرند',
    value: 'هرند',
    province_id: 4,
  },
  {
    id: 218,
    name: 'ورزنه',
    value: 'ورزنه',
    province_id: 4,
  },
  {
    id: 219,
    name: 'ورنامخواست',
    value: 'ورنامخواست',
    province_id: 4,
  },
  {
    id: 220,
    name: 'وزوان',
    value: 'وزوان',
    province_id: 4,
  },
  {
    id: 221,
    name: 'ونک',
    value: 'ونک',
    province_id: 4,
  },
  {
    id: 222,
    name: 'اسارا',
    value: 'اسارا',
    province_id: 5,
  },
  {
    id: 223,
    name: 'اشتهارد',
    value: 'اشتهارد',
    province_id: 5,
  },
  {
    id: 224,
    name: 'تنکمان',
    value: 'تنکمان',
    province_id: 5,
  },
  {
    id: 225,
    name: 'چهارباغ',
    value: 'چهارباغ',
    province_id: 5,
  },
  {
    id: 226,
    name: 'سعید آباد',
    value: 'سعید-آباد',
    province_id: 5,
  },
  {
    id: 227,
    name: 'شهر جدید هشتگرد',
    value: 'شهر-جدید-هشتگرد',
    province_id: 5,
  },
  {
    id: 228,
    name: 'طالقان',
    value: 'طالقان',
    province_id: 5,
  },
  {
    id: 229,
    name: 'کرج',
    value: 'کرج',
    province_id: 5,
  },
  {
    id: 230,
    name: 'کمال شهر',
    value: 'کمال-شهر',
    province_id: 5,
  },
  {
    id: 231,
    name: 'کوهسار',
    value: 'کوهسار',
    province_id: 5,
  },
  {
    id: 232,
    name: 'گرمدره',
    value: 'گرمدره',
    province_id: 5,
  },
  {
    id: 233,
    name: 'ماهدشت',
    value: 'ماهدشت',
    province_id: 5,
  },
  {
    id: 234,
    name: 'محمدشهر',
    value: 'البرز-محمدشهر',
    province_id: 5,
  },
  {
    id: 235,
    name: 'مشکین دشت',
    value: 'مشکین-دشت',
    province_id: 5,
  },
  {
    id: 236,
    name: 'نظرآباد',
    value: 'نظرآباد',
    province_id: 5,
  },
  {
    id: 237,
    name: 'هشتگرد',
    value: 'هشتگرد',
    province_id: 5,
  },
  {
    id: 238,
    name: 'ارکواز',
    value: 'ارکواز',
    province_id: 6,
  },
  {
    id: 239,
    name: 'ایلام',
    value: 'ایلام',
    province_id: 6,
  },
  {
    id: 240,
    name: 'ایوان',
    value: 'ایوان',
    province_id: 6,
  },
  {
    id: 241,
    name: 'آبدانان',
    value: 'آبدانان',
    province_id: 6,
  },
  {
    id: 242,
    name: 'آسمان آباد',
    value: 'آسمان-آباد',
    province_id: 6,
  },
  {
    id: 243,
    name: 'بدره',
    value: 'بدره',
    province_id: 6,
  },
  {
    id: 244,
    name: 'پهله',
    value: 'پهله',
    province_id: 6,
  },
  {
    id: 245,
    name: 'توحید',
    value: 'توحید',
    province_id: 6,
  },
  {
    id: 246,
    name: 'چوار',
    value: 'چوار',
    province_id: 6,
  },
  {
    id: 247,
    name: 'دره شهر',
    value: 'دره-شهر',
    province_id: 6,
  },
  {
    id: 248,
    name: 'دلگشا',
    value: 'دلگشا',
    province_id: 6,
  },
  {
    id: 249,
    name: 'دهلران',
    value: 'دهلران',
    province_id: 6,
  },
  {
    id: 250,
    name: 'زرنه',
    value: 'زرنه',
    province_id: 6,
  },
  {
    id: 251,
    name: 'سراب باغ',
    value: 'سراب-باغ',
    province_id: 6,
  },
  {
    id: 252,
    name: 'سرابله',
    value: 'سرابله',
    province_id: 6,
  },
  {
    id: 253,
    name: 'صالح آباد',
    value: 'ایلام-صالح-آباد',
    province_id: 6,
  },
  {
    id: 254,
    name: 'لومار',
    value: 'لومار',
    province_id: 6,
  },
  {
    id: 255,
    name: 'مهران',
    value: 'مهران',
    province_id: 6,
  },
  {
    id: 256,
    name: 'مورموری',
    value: 'مورموری',
    province_id: 6,
  },
  {
    id: 257,
    name: 'موسیان',
    value: 'موسیان',
    province_id: 6,
  },
  {
    id: 258,
    name: 'میمه',
    value: 'ایلام-میمه',
    province_id: 6,
  },
  {
    id: 259,
    name: 'امام حسن',
    value: 'امام-حسن',
    province_id: 7,
  },
  {
    id: 260,
    name: 'انارستان',
    value: 'انارستان',
    province_id: 7,
  },
  {
    id: 261,
    name: 'اهرم',
    value: 'اهرم',
    province_id: 7,
  },
  {
    id: 262,
    name: 'آب پخش',
    value: 'آب-پخش',
    province_id: 7,
  },
  {
    id: 263,
    name: 'آبدان',
    value: 'آبدان',
    province_id: 7,
  },
  {
    id: 264,
    name: 'برازجان',
    value: 'برازجان',
    province_id: 7,
  },
  {
    id: 265,
    name: 'بردخون',
    value: 'بردخون',
    province_id: 7,
  },
  {
    id: 266,
    name: 'بندردیر',
    value: 'بندردیر',
    province_id: 7,
  },
  {
    id: 267,
    name: 'بندردیلم',
    value: 'بندردیلم',
    province_id: 7,
  },
  {
    id: 268,
    name: 'بندرریگ',
    value: 'بندرریگ',
    province_id: 7,
  },
  {
    id: 269,
    name: 'بندرکنگان',
    value: 'بندرکنگان',
    province_id: 7,
  },
  {
    id: 270,
    name: 'بندرگناوه',
    value: 'بندرگناوه',
    province_id: 7,
  },
  {
    id: 271,
    name: 'بنک',
    value: 'بنک',
    province_id: 7,
  },
  {
    id: 272,
    name: 'بوشهر',
    value: 'بوشهر',
    province_id: 7,
  },
  {
    id: 273,
    name: 'تنگ ارم',
    value: 'تنگ-ارم',
    province_id: 7,
  },
  {
    id: 274,
    name: 'جم',
    value: 'جم',
    province_id: 7,
  },
  {
    id: 275,
    name: 'چغادک',
    value: 'چغادک',
    province_id: 7,
  },
  {
    id: 276,
    name: 'خارک',
    value: 'خارک',
    province_id: 7,
  },
  {
    id: 277,
    name: 'خورموج',
    value: 'خورموج',
    province_id: 7,
  },
  {
    id: 278,
    name: 'دالکی',
    value: 'دالکی',
    province_id: 7,
  },
  {
    id: 279,
    name: 'دلوار',
    value: 'دلوار',
    province_id: 7,
  },
  {
    id: 280,
    name: 'ریز',
    value: 'ریز',
    province_id: 7,
  },
  {
    id: 281,
    name: 'سعدآباد',
    value: 'سعدآباد',
    province_id: 7,
  },
  {
    id: 282,
    name: 'سیراف',
    value: 'سیراف',
    province_id: 7,
  },
  {
    id: 283,
    name: 'شبانکاره',
    value: 'شبانکاره',
    province_id: 7,
  },
  {
    id: 284,
    name: 'شنبه',
    value: 'شنبه',
    province_id: 7,
  },
  {
    id: 285,
    name: 'عسلویه',
    value: 'عسلویه',
    province_id: 7,
  },
  {
    id: 286,
    name: 'کاکی',
    value: 'کاکی',
    province_id: 7,
  },
  {
    id: 287,
    name: 'کلمه',
    value: 'کلمه',
    province_id: 7,
  },
  {
    id: 288,
    name: 'نخل تقی',
    value: 'نخل-تقی',
    province_id: 7,
  },
  {
    id: 289,
    name: 'وحدتیه',
    value: 'وحدتیه',
    province_id: 7,
  },
  {
    id: 290,
    name: 'ارجمند',
    value: 'ارجمند',
    province_id: 8,
  },
  {
    id: 291,
    name: 'اسلامشهر',
    value: 'اسلامشهر',
    province_id: 8,
  },
  {
    id: 292,
    name: 'اندیشه',
    value: 'اندیشه',
    province_id: 8,
  },
  {
    id: 293,
    name: 'آبسرد',
    value: 'آبسرد',
    province_id: 8,
  },
  {
    id: 294,
    name: 'آبعلی',
    value: 'آبعلی',
    province_id: 8,
  },
  {
    id: 295,
    name: 'باغستان',
    value: 'باغستان',
    province_id: 8,
  },
  {
    id: 296,
    name: 'باقرشهر',
    value: 'باقرشهر',
    province_id: 8,
  },
  {
    id: 297,
    name: 'بومهن',
    value: 'بومهن',
    province_id: 8,
  },
  {
    id: 298,
    name: 'پاکدشت',
    value: 'پاکدشت',
    province_id: 8,
  },
  {
    id: 299,
    name: 'پردیس',
    value: 'پردیس',
    province_id: 8,
  },
  {
    id: 300,
    name: 'پیشوا',
    value: 'پیشوا',
    province_id: 8,
  },
  {
    id: 301,
    name: 'تهران',
    value: 'تهران',
    province_id: 8,
  },
  {
    id: 302,
    name: 'جوادآباد',
    value: 'جوادآباد',
    province_id: 8,
  },
  {
    id: 303,
    name: 'چهاردانگه',
    value: 'چهاردانگه',
    province_id: 8,
  },
  {
    id: 304,
    name: 'حسن آباد',
    value: 'تهران-حسن-آباد',
    province_id: 8,
  },
  {
    id: 305,
    name: 'دماوند',
    value: 'دماوند',
    province_id: 8,
  },
  {
    id: 306,
    name: 'دیزین',
    value: 'دیزین',
    province_id: 8,
  },
  {
    id: 307,
    name: 'شهر ری',
    value: 'شهر-ری',
    province_id: 8,
  },
  {
    id: 308,
    name: 'رباط کریم',
    value: 'رباط-کریم',
    province_id: 8,
  },
  {
    id: 309,
    name: 'رودهن',
    value: 'رودهن',
    province_id: 8,
  },
  {
    id: 310,
    name: 'شاهدشهر',
    value: 'شاهدشهر',
    province_id: 8,
  },
  {
    id: 311,
    name: 'شریف آباد',
    value: 'شریف-آباد',
    province_id: 8,
  },
  {
    id: 312,
    name: 'شمشک',
    value: 'شمشک',
    province_id: 8,
  },
  {
    id: 313,
    name: 'شهریار',
    value: 'شهریار',
    province_id: 8,
  },
  {
    id: 314,
    name: 'صالح آباد',
    value: 'تهران-صالح-آباد',
    province_id: 8,
  },
  {
    id: 315,
    name: 'صباشهر',
    value: 'صباشهر',
    province_id: 8,
  },
  {
    id: 316,
    name: 'صفادشت',
    value: 'صفادشت',
    province_id: 8,
  },
  {
    id: 317,
    name: 'فردوسیه',
    value: 'فردوسیه',
    province_id: 8,
  },
  {
    id: 318,
    name: 'فشم',
    value: 'فشم',
    province_id: 8,
  },
  {
    id: 319,
    name: 'فیروزکوه',
    value: 'فیروزکوه',
    province_id: 8,
  },
  {
    id: 320,
    name: 'قدس',
    value: 'قدس',
    province_id: 8,
  },
  {
    id: 321,
    name: 'قرچک',
    value: 'قرچک',
    province_id: 8,
  },
  {
    id: 322,
    name: 'کهریزک',
    value: 'کهریزک',
    province_id: 8,
  },
  {
    id: 323,
    name: 'کیلان',
    value: 'کیلان',
    province_id: 8,
  },
  {
    id: 324,
    name: 'گلستان',
    value: 'شهر-گلستان',
    province_id: 8,
  },
  {
    id: 325,
    name: 'لواسان',
    value: 'لواسان',
    province_id: 8,
  },
  {
    id: 326,
    name: 'ملارد',
    value: 'ملارد',
    province_id: 8,
  },
  {
    id: 327,
    name: 'میگون',
    value: 'میگون',
    province_id: 8,
  },
  {
    id: 328,
    name: 'نسیم شهر',
    value: 'نسیم-شهر',
    province_id: 8,
  },
  {
    id: 329,
    name: 'نصیرآباد',
    value: 'نصیرآباد',
    province_id: 8,
  },
  {
    id: 330,
    name: 'وحیدیه',
    value: 'وحیدیه',
    province_id: 8,
  },
  {
    id: 331,
    name: 'ورامین',
    value: 'ورامین',
    province_id: 8,
  },
  {
    id: 332,
    name: 'اردل',
    value: 'اردل',
    province_id: 9,
  },
  {
    id: 333,
    name: 'آلونی',
    value: 'آلونی',
    province_id: 9,
  },
  {
    id: 334,
    name: 'باباحیدر',
    value: 'باباحیدر',
    province_id: 9,
  },
  {
    id: 335,
    name: 'بروجن',
    value: 'بروجن',
    province_id: 9,
  },
  {
    id: 336,
    name: 'بلداجی',
    value: 'بلداجی',
    province_id: 9,
  },
  {
    id: 337,
    name: 'بن',
    value: 'بن',
    province_id: 9,
  },
  {
    id: 338,
    name: 'جونقان',
    value: 'جونقان',
    province_id: 9,
  },
  {
    id: 339,
    name: 'چلگرد',
    value: 'چلگرد',
    province_id: 9,
  },
  {
    id: 340,
    name: 'سامان',
    value: 'سامان',
    province_id: 9,
  },
  {
    id: 341,
    name: 'سفیددشت',
    value: 'سفیددشت',
    province_id: 9,
  },
  {
    id: 342,
    name: 'سودجان',
    value: 'سودجان',
    province_id: 9,
  },
  {
    id: 343,
    name: 'سورشجان',
    value: 'سورشجان',
    province_id: 9,
  },
  {
    id: 344,
    name: 'شلمزار',
    value: 'شلمزار',
    province_id: 9,
  },
  {
    id: 345,
    name: 'شهرکرد',
    value: 'شهرکرد',
    province_id: 9,
  },
  {
    id: 346,
    name: 'طاقانک',
    value: 'طاقانک',
    province_id: 9,
  },
  {
    id: 347,
    name: 'فارسان',
    value: 'فارسان',
    province_id: 9,
  },
  {
    id: 348,
    name: 'فرادنبه',
    value: 'فرادبنه',
    province_id: 9,
  },
  {
    id: 349,
    name: 'فرخ شهر',
    value: 'فرخ-شهر',
    province_id: 9,
  },
  {
    id: 350,
    name: 'کیان',
    value: 'کیان',
    province_id: 9,
  },
  {
    id: 351,
    name: 'گندمان',
    value: 'گندمان',
    province_id: 9,
  },
  {
    id: 352,
    name: 'گهرو',
    value: 'گهرو',
    province_id: 9,
  },
  {
    id: 353,
    name: 'لردگان',
    value: 'لردگان',
    province_id: 9,
  },
  {
    id: 354,
    name: 'مال خلیفه',
    value: 'مال-خلیفه',
    province_id: 9,
  },
  {
    id: 355,
    name: 'ناغان',
    value: 'ناغان',
    province_id: 9,
  },
  {
    id: 356,
    name: 'نافچ',
    value: 'نافچ',
    province_id: 9,
  },
  {
    id: 357,
    name: 'نقنه',
    value: 'نقنه',
    province_id: 9,
  },
  {
    id: 358,
    name: 'هفشجان',
    value: 'هفشجان',
    province_id: 9,
  },
  {
    id: 359,
    name: 'ارسک',
    value: 'ارسک',
    province_id: 10,
  },
  {
    id: 360,
    name: 'اسدیه',
    value: 'اسدیه',
    province_id: 10,
  },
  {
    id: 361,
    name: 'اسفدن',
    value: 'اسفدن',
    province_id: 10,
  },
  {
    id: 362,
    name: 'اسلامیه',
    value: 'اسلامیه',
    province_id: 10,
  },
  {
    id: 363,
    name: 'آرین شهر',
    value: 'آرین-شهر',
    province_id: 10,
  },
  {
    id: 364,
    name: 'آیسک',
    value: 'آیسک',
    province_id: 10,
  },
  {
    id: 365,
    name: 'بشرویه',
    value: 'بشرویه',
    province_id: 10,
  },
  {
    id: 366,
    name: 'بیرجند',
    value: 'بیرجند',
    province_id: 10,
  },
  {
    id: 367,
    name: 'حاجی آباد',
    value: 'خراسان-جنوبی-حاجی-آباد',
    province_id: 10,
  },
  {
    id: 368,
    name: 'خضری دشت بیاض',
    value: 'خضری-دشت-بیاض',
    province_id: 10,
  },
  {
    id: 369,
    name: 'خوسف',
    value: 'خوسف',
    province_id: 10,
  },
  {
    id: 370,
    name: 'زهان',
    value: 'زهان',
    province_id: 10,
  },
  {
    id: 371,
    name: 'سرایان',
    value: 'سرایان',
    province_id: 10,
  },
  {
    id: 372,
    name: 'سربیشه',
    value: 'سربیشه',
    province_id: 10,
  },
  {
    id: 373,
    name: 'سه قلعه',
    value: 'سه-قلعه',
    province_id: 10,
  },
  {
    id: 374,
    name: 'شوسف',
    value: 'شوسف',
    province_id: 10,
  },
  {
    id: 375,
    name: 'طبس ',
    value: 'خراسان-جنوبی-طبس-',
    province_id: 10,
  },
  {
    id: 376,
    name: 'فردوس',
    value: 'فردوس',
    province_id: 10,
  },
  {
    id: 377,
    name: 'قاین',
    value: 'قاین',
    province_id: 10,
  },
  {
    id: 378,
    name: 'قهستان',
    value: 'قهستان',
    province_id: 10,
  },
  {
    id: 379,
    name: 'محمدشهر',
    value: 'خراسان-جنوبی-محمدشهر',
    province_id: 10,
  },
  {
    id: 380,
    name: 'مود',
    value: 'مود',
    province_id: 10,
  },
  {
    id: 381,
    name: 'نهبندان',
    value: 'نهبندان',
    province_id: 10,
  },
  {
    id: 382,
    name: 'نیمبلوک',
    value: 'نیمبلوک',
    province_id: 10,
  },
  {
    id: 383,
    name: 'احمدآباد صولت',
    value: 'احمدآباد-صولت',
    province_id: 11,
  },
  {
    id: 384,
    name: 'انابد',
    value: 'انابد',
    province_id: 11,
  },
  {
    id: 385,
    name: 'باجگیران',
    value: 'باجگیران',
    province_id: 11,
  },
  {
    id: 386,
    name: 'باخرز',
    value: 'باخرز',
    province_id: 11,
  },
  {
    id: 387,
    name: 'بار',
    value: 'بار',
    province_id: 11,
  },
  {
    id: 388,
    name: 'بایگ',
    value: 'بایگ',
    province_id: 11,
  },
  {
    id: 389,
    name: 'بجستان',
    value: 'بجستان',
    province_id: 11,
  },
  {
    id: 390,
    name: 'بردسکن',
    value: 'بردسکن',
    province_id: 11,
  },
  {
    id: 391,
    name: 'بیدخت',
    value: 'بیدخت',
    province_id: 11,
  },
  {
    id: 392,
    name: 'تایباد',
    value: 'تایباد',
    province_id: 11,
  },
  {
    id: 393,
    name: 'تربت جام',
    value: 'تربت-جام',
    province_id: 11,
  },
  {
    id: 394,
    name: 'تربت حیدریه',
    value: 'تربت-حیدریه',
    province_id: 11,
  },
  {
    id: 395,
    name: 'جغتای',
    value: 'جغتای',
    province_id: 11,
  },
  {
    id: 396,
    name: 'جنگل',
    value: 'جنگل',
    province_id: 11,
  },
  {
    id: 397,
    name: 'چاپشلو',
    value: 'چاپشلو',
    province_id: 11,
  },
  {
    id: 398,
    name: 'چکنه',
    value: 'چکنه',
    province_id: 11,
  },
  {
    id: 399,
    name: 'چناران',
    value: 'چناران',
    province_id: 11,
  },
  {
    id: 400,
    name: 'خرو',
    value: 'خرو',
    province_id: 11,
  },
  {
    id: 401,
    name: 'خلیل آباد',
    value: 'خلیل-آباد',
    province_id: 11,
  },
  {
    id: 402,
    name: 'خواف',
    value: 'خواف',
    province_id: 11,
  },
  {
    id: 403,
    name: 'داورزن',
    value: 'داورزن',
    province_id: 11,
  },
  {
    id: 404,
    name: 'درگز',
    value: 'درگز',
    province_id: 11,
  },
  {
    id: 405,
    name: 'در رود',
    value: 'در-رود',
    province_id: 11,
  },
  {
    id: 406,
    name: 'دولت آباد',
    value: 'خراسان-رضوی-دولت-آباد',
    province_id: 11,
  },
  {
    id: 407,
    name: 'رباط سنگ',
    value: 'رباط-سنگ',
    province_id: 11,
  },
  {
    id: 408,
    name: 'رشتخوار',
    value: 'رشتخوار',
    province_id: 11,
  },
  {
    id: 409,
    name: 'رضویه',
    value: 'رضویه',
    province_id: 11,
  },
  {
    id: 410,
    name: 'روداب',
    value: 'روداب',
    province_id: 11,
  },
  {
    id: 411,
    name: 'ریوش',
    value: 'ریوش',
    province_id: 11,
  },
  {
    id: 412,
    name: 'سبزوار',
    value: 'سبزوار',
    province_id: 11,
  },
  {
    id: 413,
    name: 'سرخس',
    value: 'سرخس',
    province_id: 11,
  },
  {
    id: 414,
    name: 'سفیدسنگ',
    value: 'سفیدسنگ',
    province_id: 11,
  },
  {
    id: 415,
    name: 'سلامی',
    value: 'سلامی',
    province_id: 11,
  },
  {
    id: 416,
    name: 'سلطان آباد',
    value: 'سلطان-آباد',
    province_id: 11,
  },
  {
    id: 417,
    name: 'سنگان',
    value: 'سنگان',
    province_id: 11,
  },
  {
    id: 418,
    name: 'شادمهر',
    value: 'شادمهر',
    province_id: 11,
  },
  {
    id: 419,
    name: 'شاندیز',
    value: 'شاندیز',
    province_id: 11,
  },
  {
    id: 420,
    name: 'ششتمد',
    value: 'ششتمد',
    province_id: 11,
  },
  {
    id: 421,
    name: 'شهرآباد',
    value: 'شهرآباد',
    province_id: 11,
  },
  {
    id: 422,
    name: 'شهرزو',
    value: 'شهرزو',
    province_id: 11,
  },
  {
    id: 423,
    name: 'صالح آباد',
    value: 'خراسان-رضوی-صالح-آباد',
    province_id: 11,
  },
  {
    id: 424,
    name: 'طرقبه',
    value: 'طرقبه',
    province_id: 11,
  },
  {
    id: 425,
    name: 'عشق آباد',
    value: 'خراسان-رضوی-عشق-آباد',
    province_id: 11,
  },
  {
    id: 426,
    name: 'فرهادگرد',
    value: 'فرهادگرد',
    province_id: 11,
  },
  {
    id: 427,
    name: 'فریمان',
    value: 'فریمان',
    province_id: 11,
  },
  {
    id: 428,
    name: 'فیروزه',
    value: 'فیروزه',
    province_id: 11,
  },
  {
    id: 429,
    name: 'فیض آباد',
    value: 'فیض-آباد',
    province_id: 11,
  },
  {
    id: 430,
    name: 'قاسم آباد',
    value: 'قاسم-آباد',
    province_id: 11,
  },
  {
    id: 431,
    name: 'قدمگاه',
    value: 'قدمگاه',
    province_id: 11,
  },
  {
    id: 432,
    name: 'قلندرآباد',
    value: 'قلندرآباد',
    province_id: 11,
  },
  {
    id: 433,
    name: 'قوچان',
    value: 'قوچان',
    province_id: 11,
  },
  {
    id: 434,
    name: 'کاخک',
    value: 'کاخک',
    province_id: 11,
  },
  {
    id: 435,
    name: 'کاریز',
    value: 'کاریز',
    province_id: 11,
  },
  {
    id: 436,
    name: 'کاشمر',
    value: 'کاشمر',
    province_id: 11,
  },
  {
    id: 437,
    name: 'کدکن',
    value: 'کدکن',
    province_id: 11,
  },
  {
    id: 438,
    name: 'کلات',
    value: 'کلات',
    province_id: 11,
  },
  {
    id: 439,
    name: 'کندر',
    value: 'کندر',
    province_id: 11,
  },
  {
    id: 440,
    name: 'گلمکان',
    value: 'گلمکان',
    province_id: 11,
  },
  {
    id: 441,
    name: 'گناباد',
    value: 'گناباد',
    province_id: 11,
  },
  {
    id: 442,
    name: 'لطف آباد',
    value: 'لطف-آباد',
    province_id: 11,
  },
  {
    id: 443,
    name: 'مزدآوند',
    value: 'مزدآوند',
    province_id: 11,
  },
  {
    id: 444,
    name: 'مشهد',
    value: 'مشهد',
    province_id: 11,
  },
  {
    id: 445,
    name: 'ملک آباد',
    value: 'ملک-آباد',
    province_id: 11,
  },
  {
    id: 446,
    name: 'نشتیفان',
    value: 'نشتیفان',
    province_id: 11,
  },
  {
    id: 447,
    name: 'نصرآباد',
    value: 'خراسان-رضوی-نصرآباد',
    province_id: 11,
  },
  {
    id: 448,
    name: 'نقاب',
    value: 'نقاب',
    province_id: 11,
  },
  {
    id: 449,
    name: 'نوخندان',
    value: 'نوخندان',
    province_id: 11,
  },
  {
    id: 450,
    name: 'نیشابور',
    value: 'نیشابور',
    province_id: 11,
  },
  {
    id: 451,
    name: 'نیل شهر',
    value: 'نیل-شهر',
    province_id: 11,
  },
  {
    id: 452,
    name: 'همت آباد',
    value: 'همت-آباد',
    province_id: 11,
  },
  {
    id: 453,
    name: 'یونسی',
    value: 'یونسی',
    province_id: 11,
  },
  {
    id: 454,
    name: 'اسفراین',
    value: 'اسفراین',
    province_id: 12,
  },
  {
    id: 455,
    name: 'ایور',
    value: 'ایور',
    province_id: 12,
  },
  {
    id: 456,
    name: 'آشخانه',
    value: 'آشخانه',
    province_id: 12,
  },
  {
    id: 457,
    name: 'بجنورد',
    value: 'بجنورد',
    province_id: 12,
  },
  {
    id: 458,
    name: 'پیش قلعه',
    value: 'پیش-قلعه',
    province_id: 12,
  },
  {
    id: 459,
    name: 'تیتکانلو',
    value: 'تیتکانلو',
    province_id: 12,
  },
  {
    id: 460,
    name: 'جاجرم',
    value: 'جاجرم',
    province_id: 12,
  },
  {
    id: 461,
    name: 'حصارگرمخان',
    value: 'حصارگرمخان',
    province_id: 12,
  },
  {
    id: 462,
    name: 'درق',
    value: 'درق',
    province_id: 12,
  },
  {
    id: 463,
    name: 'راز',
    value: 'راز',
    province_id: 12,
  },
  {
    id: 464,
    name: 'سنخواست',
    value: 'سنخواست',
    province_id: 12,
  },
  {
    id: 465,
    name: 'شوقان',
    value: 'شوقان',
    province_id: 12,
  },
  {
    id: 466,
    name: 'شیروان',
    value: 'شیروان',
    province_id: 12,
  },
  {
    id: 467,
    name: 'صفی آباد',
    value: 'خراسان-شمالی-صفی-آباد',
    province_id: 12,
  },
  {
    id: 468,
    name: 'فاروج',
    value: 'فاروج',
    province_id: 12,
  },
  {
    id: 469,
    name: 'قاضی',
    value: 'قاضی',
    province_id: 12,
  },
  {
    id: 470,
    name: 'گرمه',
    value: 'گرمه',
    province_id: 12,
  },
  {
    id: 471,
    name: 'لوجلی',
    value: 'لوجلی',
    province_id: 12,
  },
  {
    id: 472,
    name: 'اروندکنار',
    value: 'اروندکنار',
    province_id: 13,
  },
  {
    id: 473,
    name: 'الوان',
    value: 'الوان',
    province_id: 13,
  },
  {
    id: 474,
    name: 'امیدیه',
    value: 'امیدیه',
    province_id: 13,
  },
  {
    id: 475,
    name: 'اندیمشک',
    value: 'اندیمشک',
    province_id: 13,
  },
  {
    id: 476,
    name: 'اهواز',
    value: 'اهواز',
    province_id: 13,
  },
  {
    id: 477,
    name: 'ایذه',
    value: 'ایذه',
    province_id: 13,
  },
  {
    id: 478,
    name: 'آبادان',
    value: 'آبادان',
    province_id: 13,
  },
  {
    id: 479,
    name: 'آغاجاری',
    value: 'آغاجاری',
    province_id: 13,
  },
  {
    id: 480,
    name: 'باغ ملک',
    value: 'باغ-ملک',
    province_id: 13,
  },
  {
    id: 481,
    name: 'بستان',
    value: 'بستان',
    province_id: 13,
  },
  {
    id: 482,
    name: 'بندرامام خمینی',
    value: 'بندرامام-خمینی',
    province_id: 13,
  },
  {
    id: 483,
    name: 'بندرماهشهر',
    value: 'بندرماهشهر',
    province_id: 13,
  },
  {
    id: 484,
    name: 'بهبهان',
    value: 'بهبهان',
    province_id: 13,
  },
  {
    id: 485,
    name: 'ترکالکی',
    value: 'ترکالکی',
    province_id: 13,
  },
  {
    id: 486,
    name: 'جایزان',
    value: 'جایزان',
    province_id: 13,
  },
  {
    id: 487,
    name: 'چمران',
    value: 'چمران',
    province_id: 13,
  },
  {
    id: 488,
    name: 'چویبده',
    value: 'چویبده',
    province_id: 13,
  },
  {
    id: 489,
    name: 'حر',
    value: 'حر',
    province_id: 13,
  },
  {
    id: 490,
    name: 'حسینیه',
    value: 'حسینیه',
    province_id: 13,
  },
  {
    id: 491,
    name: 'حمزه',
    value: 'حمزه',
    province_id: 13,
  },
  {
    id: 492,
    name: 'حمیدیه',
    value: 'حمیدیه',
    province_id: 13,
  },
  {
    id: 493,
    name: 'خرمشهر',
    value: 'خرمشهر',
    province_id: 13,
  },
  {
    id: 494,
    name: 'دارخوین',
    value: 'دارخوین',
    province_id: 13,
  },
  {
    id: 495,
    name: 'دزآب',
    value: 'دزآب',
    province_id: 13,
  },
  {
    id: 496,
    name: 'دزفول',
    value: 'دزفول',
    province_id: 13,
  },
  {
    id: 497,
    name: 'دهدز',
    value: 'دهدز',
    province_id: 13,
  },
  {
    id: 498,
    name: 'رامشیر',
    value: 'رامشیر',
    province_id: 13,
  },
  {
    id: 499,
    name: 'رامهرمز',
    value: 'رامهرمز',
    province_id: 13,
  },
  {
    id: 500,
    name: 'رفیع',
    value: 'رفیع',
    province_id: 13,
  },
  {
    id: 501,
    name: 'زهره',
    value: 'زهره',
    province_id: 13,
  },
  {
    id: 502,
    name: 'سالند',
    value: 'سالند',
    province_id: 13,
  },
  {
    id: 503,
    name: 'سردشت',
    value: 'خوزستان-سردشت',
    province_id: 13,
  },
  {
    id: 504,
    name: 'سوسنگرد',
    value: 'سوسنگرد',
    province_id: 13,
  },
  {
    id: 505,
    name: 'شادگان',
    value: 'شادگان',
    province_id: 13,
  },
  {
    id: 506,
    name: 'شاوور',
    value: 'شاوور',
    province_id: 13,
  },
  {
    id: 507,
    name: 'شرافت',
    value: 'شرافت',
    province_id: 13,
  },
  {
    id: 508,
    name: 'شوش',
    value: 'شوش',
    province_id: 13,
  },
  {
    id: 509,
    name: 'شوشتر',
    value: 'شوشتر',
    province_id: 13,
  },
  {
    id: 510,
    name: 'شیبان',
    value: 'شیبان',
    province_id: 13,
  },
  {
    id: 511,
    name: 'صالح شهر',
    value: 'صالح-شهر',
    province_id: 13,
  },
  {
    id: 512,
    name: 'صفی آباد',
    value: 'خوزستان-صفی-آباد',
    province_id: 13,
  },
  {
    id: 513,
    name: 'صیدون',
    value: 'صیدون',
    province_id: 13,
  },
  {
    id: 514,
    name: 'قلعه تل',
    value: 'قلعه-تل',
    province_id: 13,
  },
  {
    id: 515,
    name: 'قلعه خواجه',
    value: 'قلعه-خواجه',
    province_id: 13,
  },
  {
    id: 516,
    name: 'گتوند',
    value: 'گتوند',
    province_id: 13,
  },
  {
    id: 517,
    name: 'لالی',
    value: 'لالی',
    province_id: 13,
  },
  {
    id: 518,
    name: 'مسجدسلیمان',
    value: 'مسجدسلیمان',
    province_id: 13,
  },
  {
    id: 520,
    name: 'ملاثانی',
    value: 'ملاثانی',
    province_id: 13,
  },
  {
    id: 521,
    name: 'میانرود',
    value: 'میانرود',
    province_id: 13,
  },
  {
    id: 522,
    name: 'مینوشهر',
    value: 'مینوشهر',
    province_id: 13,
  },
  {
    id: 523,
    name: 'هفتگل',
    value: 'هفتگل',
    province_id: 13,
  },
  {
    id: 524,
    name: 'هندیجان',
    value: 'هندیجان',
    province_id: 13,
  },
  {
    id: 525,
    name: 'هویزه',
    value: 'هویزه',
    province_id: 13,
  },
  {
    id: 526,
    name: 'ویس',
    value: 'ویس',
    province_id: 13,
  },
  {
    id: 527,
    name: 'ابهر',
    value: 'ابهر',
    province_id: 14,
  },
  {
    id: 528,
    name: 'ارمغان خانه',
    value: 'ارمغان-خانه',
    province_id: 14,
  },
  {
    id: 529,
    name: 'آب بر',
    value: 'آب-بر',
    province_id: 14,
  },
  {
    id: 530,
    name: 'چورزق',
    value: 'چورزق',
    province_id: 14,
  },
  {
    id: 531,
    name: 'حلب',
    value: 'حلب',
    province_id: 14,
  },
  {
    id: 532,
    name: 'خرمدره',
    value: 'خرمدره',
    province_id: 14,
  },
  {
    id: 533,
    name: 'دندی',
    value: 'دندی',
    province_id: 14,
  },
  {
    id: 534,
    name: 'زرین آباد',
    value: 'زرین-آباد',
    province_id: 14,
  },
  {
    id: 535,
    name: 'زرین رود',
    value: 'زرین-رود',
    province_id: 14,
  },
  {
    id: 536,
    name: 'زنجان',
    value: 'زنجان',
    province_id: 14,
  },
  {
    id: 537,
    name: 'سجاس',
    value: 'سجاس',
    province_id: 14,
  },
  {
    id: 538,
    name: 'سلطانیه',
    value: 'سلطانیه',
    province_id: 14,
  },
  {
    id: 539,
    name: 'سهرورد',
    value: 'سهرورد',
    province_id: 14,
  },
  {
    id: 540,
    name: 'صائین قلعه',
    value: 'صائین-قلعه',
    province_id: 14,
  },
  {
    id: 541,
    name: 'قیدار',
    value: 'قیدار',
    province_id: 14,
  },
  {
    id: 542,
    name: 'گرماب',
    value: 'گرماب',
    province_id: 14,
  },
  {
    id: 543,
    name: 'ماه نشان',
    value: 'ماه-نشان',
    province_id: 14,
  },
  {
    id: 544,
    name: 'هیدج',
    value: 'هیدج',
    province_id: 14,
  },
  {
    id: 545,
    name: 'امیریه',
    value: 'امیریه',
    province_id: 15,
  },
  {
    id: 546,
    name: 'ایوانکی',
    value: 'ایوانکی',
    province_id: 15,
  },
  {
    id: 547,
    name: 'آرادان',
    value: 'آرادان',
    province_id: 15,
  },
  {
    id: 548,
    name: 'بسطام',
    value: 'بسطام',
    province_id: 15,
  },
  {
    id: 549,
    name: 'بیارجمند',
    value: 'بیارجمند',
    province_id: 15,
  },
  {
    id: 550,
    name: 'دامغان',
    value: 'دامغان',
    province_id: 15,
  },
  {
    id: 551,
    name: 'درجزین',
    value: 'درجزین',
    province_id: 15,
  },
  {
    id: 552,
    name: 'دیباج',
    value: 'دیباج',
    province_id: 15,
  },
  {
    id: 553,
    name: 'سرخه',
    value: 'سرخه',
    province_id: 15,
  },
  {
    id: 554,
    name: 'سمنان',
    value: 'سمنان',
    province_id: 15,
  },
  {
    id: 555,
    name: 'شاهرود',
    value: 'شاهرود',
    province_id: 15,
  },
  {
    id: 556,
    name: 'شهمیرزاد',
    value: 'شهمیرزاد',
    province_id: 15,
  },
  {
    id: 557,
    name: 'کلاته خیج',
    value: 'کلاته-خیج',
    province_id: 15,
  },
  {
    id: 558,
    name: 'گرمسار',
    value: 'گرمسار',
    province_id: 15,
  },
  {
    id: 559,
    name: 'مجن',
    value: 'مجن',
    province_id: 15,
  },
  {
    id: 560,
    name: 'مهدی شهر',
    value: 'مهدی-شهر',
    province_id: 15,
  },
  {
    id: 561,
    name: 'میامی',
    value: 'میامی',
    province_id: 15,
  },
  {
    id: 562,
    name: 'ادیمی',
    value: 'ادیمی',
    province_id: 16,
  },
  {
    id: 563,
    name: 'اسپکه',
    value: 'اسپکه',
    province_id: 16,
  },
  {
    id: 564,
    name: 'ایرانشهر',
    value: 'ایرانشهر',
    province_id: 16,
  },
  {
    id: 565,
    name: 'بزمان',
    value: 'بزمان',
    province_id: 16,
  },
  {
    id: 566,
    name: 'بمپور',
    value: 'بمپور',
    province_id: 16,
  },
  {
    id: 567,
    name: 'بنت',
    value: 'بنت',
    province_id: 16,
  },
  {
    id: 568,
    name: 'بنجار',
    value: 'بنجار',
    province_id: 16,
  },
  {
    id: 569,
    name: 'پیشین',
    value: 'پیشین',
    province_id: 16,
  },
  {
    id: 570,
    name: 'جالق',
    value: 'جالق',
    province_id: 16,
  },
  {
    id: 571,
    name: 'چابهار',
    value: 'چابهار',
    province_id: 16,
  },
  {
    id: 572,
    name: 'خاش',
    value: 'خاش',
    province_id: 16,
  },
  {
    id: 573,
    name: 'دوست محمد',
    value: 'دوست-محمد',
    province_id: 16,
  },
  {
    id: 574,
    name: 'راسک',
    value: 'راسک',
    province_id: 16,
  },
  {
    id: 575,
    name: 'زابل',
    value: 'زابل',
    province_id: 16,
  },
  {
    id: 576,
    name: 'زابلی',
    value: 'زابلی',
    province_id: 16,
  },
  {
    id: 577,
    name: 'زاهدان',
    value: 'زاهدان',
    province_id: 16,
  },
  {
    id: 578,
    name: 'زهک',
    value: 'زهک',
    province_id: 16,
  },
  {
    id: 579,
    name: 'سراوان',
    value: 'سراوان',
    province_id: 16,
  },
  {
    id: 580,
    name: 'سرباز',
    value: 'سرباز',
    province_id: 16,
  },
  {
    id: 581,
    name: 'سوران',
    value: 'سوران',
    province_id: 16,
  },
  {
    id: 582,
    name: 'سیرکان',
    value: 'سیرکان',
    province_id: 16,
  },
  {
    id: 583,
    name: 'علی اکبر',
    value: 'علی-اکبر',
    province_id: 16,
  },
  {
    id: 584,
    name: 'فنوج',
    value: 'فنوج',
    province_id: 16,
  },
  {
    id: 585,
    name: 'قصرقند',
    value: 'قصرقند',
    province_id: 16,
  },
  {
    id: 586,
    name: 'کنارک',
    value: 'کنارک',
    province_id: 16,
  },
  {
    id: 587,
    name: 'گشت',
    value: 'گشت',
    province_id: 16,
  },
  {
    id: 588,
    name: 'گلمورتی',
    value: 'گلمورتی',
    province_id: 16,
  },
  {
    id: 589,
    name: 'محمدان',
    value: 'محمدان',
    province_id: 16,
  },
  {
    id: 590,
    name: 'محمدآباد',
    value: 'سیستان-و-بلوچستان-محمدآباد',
    province_id: 16,
  },
  {
    id: 591,
    name: 'محمدی',
    value: 'محمدی',
    province_id: 16,
  },
  {
    id: 592,
    name: 'میرجاوه',
    value: 'میرجاوه',
    province_id: 16,
  },
  {
    id: 593,
    name: 'نصرت آباد',
    value: 'نصرت-آباد',
    province_id: 16,
  },
  {
    id: 594,
    name: 'نگور',
    value: 'نگور',
    province_id: 16,
  },
  {
    id: 595,
    name: 'نوک آباد',
    value: 'نوک-آباد',
    province_id: 16,
  },
  {
    id: 596,
    name: 'نیک شهر',
    value: 'نیک-شهر',
    province_id: 16,
  },
  {
    id: 597,
    name: 'هیدوچ',
    value: 'هیدوچ',
    province_id: 16,
  },
  {
    id: 598,
    name: 'اردکان',
    value: 'فارس-اردکان',
    province_id: 17,
  },
  {
    id: 599,
    name: 'ارسنجان',
    value: 'ارسنجان',
    province_id: 17,
  },
  {
    id: 600,
    name: 'استهبان',
    value: 'استهبان',
    province_id: 17,
  },
  {
    id: 601,
    name: 'اشکنان',
    value: 'اشکنان',
    province_id: 17,
  },
  {
    id: 602,
    name: 'افزر',
    value: 'افزر',
    province_id: 17,
  },
  {
    id: 603,
    name: 'اقلید',
    value: 'اقلید',
    province_id: 17,
  },
  {
    id: 604,
    name: 'امام شهر',
    value: 'امام-شهر',
    province_id: 17,
  },
  {
    id: 605,
    name: 'اهل',
    value: 'اهل',
    province_id: 17,
  },
  {
    id: 606,
    name: 'اوز',
    value: 'اوز',
    province_id: 17,
  },
  {
    id: 607,
    name: 'ایج',
    value: 'ایج',
    province_id: 17,
  },
  {
    id: 608,
    name: 'ایزدخواست',
    value: 'ایزدخواست',
    province_id: 17,
  },
  {
    id: 609,
    name: 'آباده',
    value: 'آباده',
    province_id: 17,
  },
  {
    id: 610,
    name: 'آباده طشک',
    value: 'آباده-طشک',
    province_id: 17,
  },
  {
    id: 611,
    name: 'باب انار',
    value: 'باب-انار',
    province_id: 17,
  },
  {
    id: 612,
    name: 'بالاده',
    value: 'فارس-بالاده',
    province_id: 17,
  },
  {
    id: 613,
    name: 'بنارویه',
    value: 'بنارویه',
    province_id: 17,
  },
  {
    id: 614,
    name: 'بهمن',
    value: 'بهمن',
    province_id: 17,
  },
  {
    id: 615,
    name: 'بوانات',
    value: 'بوانات',
    province_id: 17,
  },
  {
    id: 616,
    name: 'بیرم',
    value: 'بیرم',
    province_id: 17,
  },
  {
    id: 617,
    name: 'بیضا',
    value: 'بیضا',
    province_id: 17,
  },
  {
    id: 618,
    name: 'جنت شهر',
    value: 'جنت-شهر',
    province_id: 17,
  },
  {
    id: 619,
    name: 'جهرم',
    value: 'جهرم',
    province_id: 17,
  },
  {
    id: 620,
    name: 'جویم',
    value: 'جویم',
    province_id: 17,
  },
  {
    id: 621,
    name: 'زرین دشت',
    value: 'زرین-دشت',
    province_id: 17,
  },
  {
    id: 622,
    name: 'حسن آباد',
    value: 'فارس-حسن-آباد',
    province_id: 17,
  },
  {
    id: 623,
    name: 'خان زنیان',
    value: 'خان-زنیان',
    province_id: 17,
  },
  {
    id: 624,
    name: 'خاوران',
    value: 'خاوران',
    province_id: 17,
  },
  {
    id: 625,
    name: 'خرامه',
    value: 'خرامه',
    province_id: 17,
  },
  {
    id: 626,
    name: 'خشت',
    value: 'خشت',
    province_id: 17,
  },
  {
    id: 627,
    name: 'خنج',
    value: 'خنج',
    province_id: 17,
  },
  {
    id: 628,
    name: 'خور',
    value: 'فارس-خور',
    province_id: 17,
  },
  {
    id: 629,
    name: 'داراب',
    value: 'داراب',
    province_id: 17,
  },
  {
    id: 630,
    name: 'داریان',
    value: 'داریان',
    province_id: 17,
  },
  {
    id: 631,
    name: 'دبیران',
    value: 'دبیران',
    province_id: 17,
  },
  {
    id: 632,
    name: 'دژکرد',
    value: 'دژکرد',
    province_id: 17,
  },
  {
    id: 633,
    name: 'دهرم',
    value: 'دهرم',
    province_id: 17,
  },
  {
    id: 634,
    name: 'دوبرجی',
    value: 'دوبرجی',
    province_id: 17,
  },
  {
    id: 635,
    name: 'رامجرد',
    value: 'رامجرد',
    province_id: 17,
  },
  {
    id: 636,
    name: 'رونیز',
    value: 'رونیز',
    province_id: 17,
  },
  {
    id: 637,
    name: 'زاهدشهر',
    value: 'زاهدشهر',
    province_id: 17,
  },
  {
    id: 638,
    name: 'زرقان',
    value: 'زرقان',
    province_id: 17,
  },
  {
    id: 639,
    name: 'سده',
    value: 'سده',
    province_id: 17,
  },
  {
    id: 640,
    name: 'سروستان',
    value: 'سروستان',
    province_id: 17,
  },
  {
    id: 641,
    name: 'سعادت شهر',
    value: 'سعادت-شهر',
    province_id: 17,
  },
  {
    id: 642,
    name: 'سورمق',
    value: 'سورمق',
    province_id: 17,
  },
  {
    id: 643,
    name: 'سیدان',
    value: 'سیدان',
    province_id: 17,
  },
  {
    id: 644,
    name: 'ششده',
    value: 'ششده',
    province_id: 17,
  },
  {
    id: 645,
    name: 'شهرپیر',
    value: 'شهرپیر',
    province_id: 17,
  },
  {
    id: 646,
    name: 'شهرصدرا',
    value: 'شهرصدرا',
    province_id: 17,
  },
  {
    id: 647,
    name: 'شیراز',
    value: 'شیراز',
    province_id: 17,
  },
  {
    id: 648,
    name: 'صغاد',
    value: 'صغاد',
    province_id: 17,
  },
  {
    id: 649,
    name: 'صفاشهر',
    value: 'صفاشهر',
    province_id: 17,
  },
  {
    id: 650,
    name: 'علامرودشت',
    value: 'علامرودشت',
    province_id: 17,
  },
  {
    id: 651,
    name: 'فدامی',
    value: 'فدامی',
    province_id: 17,
  },
  {
    id: 652,
    name: 'فراشبند',
    value: 'فراشبند',
    province_id: 17,
  },
  {
    id: 653,
    name: 'فسا',
    value: 'فسا',
    province_id: 17,
  },
  {
    id: 654,
    name: 'فیروزآباد',
    value: 'فارس-فیروزآباد',
    province_id: 17,
  },
  {
    id: 655,
    name: 'قائمیه',
    value: 'قائمیه',
    province_id: 17,
  },
  {
    id: 656,
    name: 'قادرآباد',
    value: 'قادرآباد',
    province_id: 17,
  },
  {
    id: 657,
    name: 'قطب آباد',
    value: 'قطب-آباد',
    province_id: 17,
  },
  {
    id: 658,
    name: 'قطرویه',
    value: 'قطرویه',
    province_id: 17,
  },
  {
    id: 659,
    name: 'قیر',
    value: 'قیر',
    province_id: 17,
  },
  {
    id: 660,
    name: 'کارزین (فتح آباد)',
    value: 'کارزین-فتح-آباد',
    province_id: 17,
  },
  {
    id: 661,
    name: 'کازرون',
    value: 'کازرون',
    province_id: 17,
  },
  {
    id: 662,
    name: 'کامفیروز',
    value: 'کامفیروز',
    province_id: 17,
  },
  {
    id: 663,
    name: 'کره ای',
    value: 'کره-ای',
    province_id: 17,
  },
  {
    id: 664,
    name: 'کنارتخته',
    value: 'کنارتخته',
    province_id: 17,
  },
  {
    id: 665,
    name: 'کوار',
    value: 'کوار',
    province_id: 17,
  },
  {
    id: 666,
    name: 'گراش',
    value: 'گراش',
    province_id: 17,
  },
  {
    id: 667,
    name: 'گله دار',
    value: 'گله-دار',
    province_id: 17,
  },
  {
    id: 668,
    name: 'لار',
    value: 'لار',
    province_id: 17,
  },
  {
    id: 669,
    name: 'لامرد',
    value: 'لامرد',
    province_id: 17,
  },
  {
    id: 670,
    name: 'لپویی',
    value: 'لپویی',
    province_id: 17,
  },
  {
    id: 671,
    name: 'لطیفی',
    value: 'لطیفی',
    province_id: 17,
  },
  {
    id: 672,
    name: 'مبارک آباددیز',
    value: 'مبارک-آباددیز',
    province_id: 17,
  },
  {
    id: 673,
    name: 'مرودشت',
    value: 'مرودشت',
    province_id: 17,
  },
  {
    id: 674,
    name: 'مشکان',
    value: 'مشکان',
    province_id: 17,
  },
  {
    id: 675,
    name: 'مصیری',
    value: 'مصیری',
    province_id: 17,
  },
  {
    id: 676,
    name: 'مهر',
    value: 'مهر',
    province_id: 17,
  },
  {
    id: 677,
    name: 'میمند',
    value: 'میمند',
    province_id: 17,
  },
  {
    id: 678,
    name: 'نوبندگان',
    value: 'نوبندگان',
    province_id: 17,
  },
  {
    id: 679,
    name: 'نوجین',
    value: 'نوجین',
    province_id: 17,
  },
  {
    id: 680,
    name: 'نودان',
    value: 'نودان',
    province_id: 17,
  },
  {
    id: 681,
    name: 'نورآباد',
    value: 'فارس-نورآباد',
    province_id: 17,
  },
  {
    id: 682,
    name: 'نی ریز',
    value: 'نی-ریز',
    province_id: 17,
  },
  {
    id: 683,
    name: 'وراوی',
    value: 'وراوی',
    province_id: 17,
  },
  {
    id: 684,
    name: 'ارداق',
    value: 'ارداق',
    province_id: 18,
  },
  {
    id: 685,
    name: 'اسفرورین',
    value: 'اسفرورین',
    province_id: 18,
  },
  {
    id: 686,
    name: 'اقبالیه',
    value: 'اقبالیه',
    province_id: 18,
  },
  {
    id: 687,
    name: 'الوند',
    value: 'الوند',
    province_id: 18,
  },
  {
    id: 688,
    name: 'آبگرم',
    value: 'آبگرم',
    province_id: 18,
  },
  {
    id: 689,
    name: 'آبیک',
    value: 'آبیک',
    province_id: 18,
  },
  {
    id: 690,
    name: 'آوج',
    value: 'آوج',
    province_id: 18,
  },
  {
    id: 691,
    name: 'بوئین زهرا',
    value: 'بوئین-زهرا',
    province_id: 18,
  },
  {
    id: 692,
    name: 'بیدستان',
    value: 'بیدستان',
    province_id: 18,
  },
  {
    id: 693,
    name: 'تاکستان',
    value: 'تاکستان',
    province_id: 18,
  },
  {
    id: 694,
    name: 'خاکعلی',
    value: 'خاکعلی',
    province_id: 18,
  },
  {
    id: 695,
    name: 'خرمدشت',
    value: 'خرمدشت',
    province_id: 18,
  },
  {
    id: 696,
    name: 'دانسفهان',
    value: 'دانسفهان',
    province_id: 18,
  },
  {
    id: 697,
    name: 'رازمیان',
    value: 'رازمیان',
    province_id: 18,
  },
  {
    id: 698,
    name: 'سگزآباد',
    value: 'سگزآباد',
    province_id: 18,
  },
  {
    id: 699,
    name: 'سیردان',
    value: 'سیردان',
    province_id: 18,
  },
  {
    id: 700,
    name: 'شال',
    value: 'شال',
    province_id: 18,
  },
  {
    id: 701,
    name: 'شریفیه',
    value: 'شریفیه',
    province_id: 18,
  },
  {
    id: 702,
    name: 'ضیاآباد',
    value: 'ضیاآباد',
    province_id: 18,
  },
  {
    id: 703,
    name: 'قزوین',
    value: 'قزوین',
    province_id: 18,
  },
  {
    id: 704,
    name: 'کوهین',
    value: 'کوهین',
    province_id: 18,
  },
  {
    id: 705,
    name: 'محمدیه',
    value: 'محمدیه',
    province_id: 18,
  },
  {
    id: 706,
    name: 'محمودآباد نمونه',
    value: 'محمودآباد-نمونه',
    province_id: 18,
  },
  {
    id: 707,
    name: 'معلم کلایه',
    value: 'معلم-کلایه',
    province_id: 18,
  },
  {
    id: 708,
    name: 'نرجه',
    value: 'نرجه',
    province_id: 18,
  },
  {
    id: 709,
    name: 'جعفریه',
    value: 'جعفریه',
    province_id: 19,
  },
  {
    id: 710,
    name: 'دستجرد',
    value: 'دستجرد',
    province_id: 19,
  },
  {
    id: 711,
    name: 'سلفچگان',
    value: 'سلفچگان',
    province_id: 19,
  },
  {
    id: 712,
    name: 'قم',
    value: 'قم',
    province_id: 19,
  },
  {
    id: 713,
    name: 'قنوات',
    value: 'قنوات',
    province_id: 19,
  },
  {
    id: 714,
    name: 'کهک',
    value: 'کهک',
    province_id: 19,
  },
  {
    id: 715,
    name: 'آرمرده',
    value: 'آرمرده',
    province_id: 20,
  },
  {
    id: 716,
    name: 'بابارشانی',
    value: 'بابارشانی',
    province_id: 20,
  },
  {
    id: 717,
    name: 'بانه',
    value: 'بانه',
    province_id: 20,
  },
  {
    id: 718,
    name: 'بلبان آباد',
    value: 'بلبان-آباد',
    province_id: 20,
  },
  {
    id: 719,
    name: 'بوئین سفلی',
    value: 'بوئین-سفلی',
    province_id: 20,
  },
  {
    id: 720,
    name: 'بیجار',
    value: 'بیجار',
    province_id: 20,
  },
  {
    id: 721,
    name: 'چناره',
    value: 'چناره',
    province_id: 20,
  },
  {
    id: 722,
    name: 'دزج',
    value: 'دزج',
    province_id: 20,
  },
  {
    id: 723,
    name: 'دلبران',
    value: 'دلبران',
    province_id: 20,
  },
  {
    id: 724,
    name: 'دهگلان',
    value: 'دهگلان',
    province_id: 20,
  },
  {
    id: 725,
    name: 'دیواندره',
    value: 'دیواندره',
    province_id: 20,
  },
  {
    id: 726,
    name: 'زرینه',
    value: 'زرینه',
    province_id: 20,
  },
  {
    id: 727,
    name: 'سروآباد',
    value: 'سروآباد',
    province_id: 20,
  },
  {
    id: 728,
    name: 'سریش آباد',
    value: 'سریش-آباد',
    province_id: 20,
  },
  {
    id: 729,
    name: 'سقز',
    value: 'سقز',
    province_id: 20,
  },
  {
    id: 730,
    name: 'سنندج',
    value: 'سنندج',
    province_id: 20,
  },
  {
    id: 731,
    name: 'شویشه',
    value: 'شویشه',
    province_id: 20,
  },
  {
    id: 732,
    name: 'صاحب',
    value: 'صاحب',
    province_id: 20,
  },
  {
    id: 733,
    name: 'قروه',
    value: 'قروه',
    province_id: 20,
  },
  {
    id: 734,
    name: 'کامیاران',
    value: 'کامیاران',
    province_id: 20,
  },
  {
    id: 735,
    name: 'کانی دینار',
    value: 'کانی-دینار',
    province_id: 20,
  },
  {
    id: 736,
    name: 'کانی سور',
    value: 'کانی-سور',
    province_id: 20,
  },
  {
    id: 737,
    name: 'مریوان',
    value: 'مریوان',
    province_id: 20,
  },
  {
    id: 738,
    name: 'موچش',
    value: 'موچش',
    province_id: 20,
  },
  {
    id: 739,
    name: 'یاسوکند',
    value: 'یاسوکند',
    province_id: 20,
  },
  {
    id: 740,
    name: 'اختیارآباد',
    value: 'اختیارآباد',
    province_id: 21,
  },
  {
    id: 741,
    name: 'ارزوئیه',
    value: 'ارزوئیه',
    province_id: 21,
  },
  {
    id: 742,
    name: 'امین شهر',
    value: 'امین-شهر',
    province_id: 21,
  },
  {
    id: 743,
    name: 'انار',
    value: 'انار',
    province_id: 21,
  },
  {
    id: 744,
    name: 'اندوهجرد',
    value: 'اندوهجرد',
    province_id: 21,
  },
  {
    id: 745,
    name: 'باغین',
    value: 'باغین',
    province_id: 21,
  },
  {
    id: 746,
    name: 'بافت',
    value: 'بافت',
    province_id: 21,
  },
  {
    id: 747,
    name: 'بردسیر',
    value: 'بردسیر',
    province_id: 21,
  },
  {
    id: 748,
    name: 'بروات',
    value: 'بروات',
    province_id: 21,
  },
  {
    id: 749,
    name: 'بزنجان',
    value: 'بزنجان',
    province_id: 21,
  },
  {
    id: 750,
    name: 'بم',
    value: 'بم',
    province_id: 21,
  },
  {
    id: 751,
    name: 'بهرمان',
    value: 'بهرمان',
    province_id: 21,
  },
  {
    id: 752,
    name: 'پاریز',
    value: 'پاریز',
    province_id: 21,
  },
  {
    id: 753,
    name: 'جبالبارز',
    value: 'جبالبارز',
    province_id: 21,
  },
  {
    id: 754,
    name: 'جوپار',
    value: 'جوپار',
    province_id: 21,
  },
  {
    id: 755,
    name: 'جوزم',
    value: 'جوزم',
    province_id: 21,
  },
  {
    id: 756,
    name: 'جیرفت',
    value: 'جیرفت',
    province_id: 21,
  },
  {
    id: 757,
    name: 'چترود',
    value: 'چترود',
    province_id: 21,
  },
  {
    id: 758,
    name: 'خاتون آباد',
    value: 'خاتون-آباد',
    province_id: 21,
  },
  {
    id: 759,
    name: 'خانوک',
    value: 'خانوک',
    province_id: 21,
  },
  {
    id: 760,
    name: 'خورسند',
    value: 'خورسند',
    province_id: 21,
  },
  {
    id: 761,
    name: 'درب بهشت',
    value: 'درب-بهشت',
    province_id: 21,
  },
  {
    id: 762,
    name: 'دهج',
    value: 'دهج',
    province_id: 21,
  },
  {
    id: 763,
    name: 'رابر',
    value: 'رابر',
    province_id: 21,
  },
  {
    id: 764,
    name: 'راور',
    value: 'راور',
    province_id: 21,
  },
  {
    id: 765,
    name: 'راین',
    value: 'راین',
    province_id: 21,
  },
  {
    id: 766,
    name: 'رفسنجان',
    value: 'رفسنجان',
    province_id: 21,
  },
  {
    id: 767,
    name: 'رودبار',
    value: 'کرمان-رودبار',
    province_id: 21,
  },
  {
    id: 768,
    name: 'ریحان شهر',
    value: 'ریحان-شهر',
    province_id: 21,
  },
  {
    id: 769,
    name: 'زرند',
    value: 'زرند',
    province_id: 21,
  },
  {
    id: 770,
    name: 'زنگی آباد',
    value: 'زنگی-آباد',
    province_id: 21,
  },
  {
    id: 771,
    name: 'زیدآباد',
    value: 'زیدآباد',
    province_id: 21,
  },
  {
    id: 772,
    name: 'سیرجان',
    value: 'سیرجان',
    province_id: 21,
  },
  {
    id: 773,
    name: 'شهداد',
    value: 'شهداد',
    province_id: 21,
  },
  {
    id: 774,
    name: 'شهربابک',
    value: 'شهربابک',
    province_id: 21,
  },
  {
    id: 775,
    name: 'صفائیه',
    value: 'صفائیه',
    province_id: 21,
  },
  {
    id: 776,
    name: 'عنبرآباد',
    value: 'عنبرآباد',
    province_id: 21,
  },
  {
    id: 777,
    name: 'فاریاب',
    value: 'فاریاب',
    province_id: 21,
  },
  {
    id: 778,
    name: 'فهرج',
    value: 'فهرج',
    province_id: 21,
  },
  {
    id: 779,
    name: 'قلعه گنج',
    value: 'قلعه-گنج',
    province_id: 21,
  },
  {
    id: 780,
    name: 'کاظم آباد',
    value: 'کاظم-آباد',
    province_id: 21,
  },
  {
    id: 781,
    name: 'کرمان',
    value: 'کرمان',
    province_id: 21,
  },
  {
    id: 782,
    name: 'کشکوئیه',
    value: 'کشکوئیه',
    province_id: 21,
  },
  {
    id: 783,
    name: 'کهنوج',
    value: 'کهنوج',
    province_id: 21,
  },
  {
    id: 784,
    name: 'کوهبنان',
    value: 'کوهبنان',
    province_id: 21,
  },
  {
    id: 785,
    name: 'کیانشهر',
    value: 'کیانشهر',
    province_id: 21,
  },
  {
    id: 786,
    name: 'گلباف',
    value: 'گلباف',
    province_id: 21,
  },
  {
    id: 787,
    name: 'گلزار',
    value: 'گلزار',
    province_id: 21,
  },
  {
    id: 788,
    name: 'لاله زار',
    value: 'لاله-زار',
    province_id: 21,
  },
  {
    id: 789,
    name: 'ماهان',
    value: 'ماهان',
    province_id: 21,
  },
  {
    id: 790,
    name: 'محمدآباد',
    value: 'کرمان-محمدآباد',
    province_id: 21,
  },
  {
    id: 791,
    name: 'محی آباد',
    value: 'محی-آباد',
    province_id: 21,
  },
  {
    id: 792,
    name: 'مردهک',
    value: 'مردهک',
    province_id: 21,
  },
  {
    id: 793,
    name: 'مس سرچشمه',
    value: 'مس-سرچشمه',
    province_id: 21,
  },
  {
    id: 794,
    name: 'منوجان',
    value: 'منوجان',
    province_id: 21,
  },
  {
    id: 795,
    name: 'نجف شهر',
    value: 'نجف-شهر',
    province_id: 21,
  },
  {
    id: 796,
    name: 'نرماشیر',
    value: 'نرماشیر',
    province_id: 21,
  },
  {
    id: 797,
    name: 'نظام شهر',
    value: 'نظام-شهر',
    province_id: 21,
  },
  {
    id: 798,
    name: 'نگار',
    value: 'نگار',
    province_id: 21,
  },
  {
    id: 799,
    name: 'نودژ',
    value: 'نودژ',
    province_id: 21,
  },
  {
    id: 800,
    name: 'هجدک',
    value: 'هجدک',
    province_id: 21,
  },
  {
    id: 801,
    name: 'یزدان شهر',
    value: 'یزدان-شهر',
    province_id: 21,
  },
  {
    id: 802,
    name: 'ازگله',
    value: 'ازگله',
    province_id: 22,
  },
  {
    id: 803,
    name: 'اسلام آباد غرب',
    value: 'اسلام-آباد-غرب',
    province_id: 22,
  },
  {
    id: 804,
    name: 'باینگان',
    value: 'باینگان',
    province_id: 22,
  },
  {
    id: 805,
    name: 'بیستون',
    value: 'بیستون',
    province_id: 22,
  },
  {
    id: 806,
    name: 'پاوه',
    value: 'پاوه',
    province_id: 22,
  },
  {
    id: 807,
    name: 'تازه آباد',
    value: 'تازه-آباد',
    province_id: 22,
  },
  {
    id: 808,
    name: 'جوان رود',
    value: 'جوان-رود',
    province_id: 22,
  },
  {
    id: 809,
    name: 'حمیل',
    value: 'حمیل',
    province_id: 22,
  },
  {
    id: 810,
    name: 'ماهیدشت',
    value: 'ماهیدشت',
    province_id: 22,
  },
  {
    id: 811,
    name: 'روانسر',
    value: 'روانسر',
    province_id: 22,
  },
  {
    id: 812,
    name: 'سرپل ذهاب',
    value: 'سرپل-ذهاب',
    province_id: 22,
  },
  {
    id: 813,
    name: 'سرمست',
    value: 'سرمست',
    province_id: 22,
  },
  {
    id: 814,
    name: 'سطر',
    value: 'سطر',
    province_id: 22,
  },
  {
    id: 815,
    name: 'سنقر',
    value: 'سنقر',
    province_id: 22,
  },
  {
    id: 816,
    name: 'سومار',
    value: 'سومار',
    province_id: 22,
  },
  {
    id: 817,
    name: 'شاهو',
    value: 'شاهو',
    province_id: 22,
  },
  {
    id: 818,
    name: 'صحنه',
    value: 'صحنه',
    province_id: 22,
  },
  {
    id: 819,
    name: 'قصرشیرین',
    value: 'قصرشیرین',
    province_id: 22,
  },
  {
    id: 820,
    name: 'کرمانشاه',
    value: 'کرمانشاه',
    province_id: 22,
  },
  {
    id: 821,
    name: 'کرندغرب',
    value: 'کرندغرب',
    province_id: 22,
  },
  {
    id: 822,
    name: 'کنگاور',
    value: 'کنگاور',
    province_id: 22,
  },
  {
    id: 823,
    name: 'کوزران',
    value: 'کوزران',
    province_id: 22,
  },
  {
    id: 824,
    name: 'گهواره',
    value: 'گهواره',
    province_id: 22,
  },
  {
    id: 825,
    name: 'گیلانغرب',
    value: 'گیلانغرب',
    province_id: 22,
  },
  {
    id: 826,
    name: 'میان راهان',
    value: 'میان-راهان',
    province_id: 22,
  },
  {
    id: 827,
    name: 'نودشه',
    value: 'نودشه',
    province_id: 22,
  },
  {
    id: 828,
    name: 'نوسود',
    value: 'نوسود',
    province_id: 22,
  },
  {
    id: 829,
    name: 'هرسین',
    value: 'هرسین',
    province_id: 22,
  },
  {
    id: 830,
    name: 'هلشی',
    value: 'هلشی',
    province_id: 22,
  },
  {
    id: 831,
    name: 'باشت',
    value: 'باشت',
    province_id: 23,
  },
  {
    id: 832,
    name: 'پاتاوه',
    value: 'پاتاوه',
    province_id: 23,
  },
  {
    id: 833,
    name: 'چرام',
    value: 'چرام',
    province_id: 23,
  },
  {
    id: 834,
    name: 'چیتاب',
    value: 'چیتاب',
    province_id: 23,
  },
  {
    id: 835,
    name: 'دهدشت',
    value: 'دهدشت',
    province_id: 23,
  },
  {
    id: 836,
    name: 'دوگنبدان',
    value: 'دوگنبدان',
    province_id: 23,
  },
  {
    id: 837,
    name: 'دیشموک',
    value: 'دیشموک',
    province_id: 23,
  },
  {
    id: 838,
    name: 'سوق',
    value: 'سوق',
    province_id: 23,
  },
  {
    id: 839,
    name: 'سی سخت',
    value: 'سی-سخت',
    province_id: 23,
  },
  {
    id: 840,
    name: 'قلعه رئیسی',
    value: 'قلعه-رئیسی',
    province_id: 23,
  },
  {
    id: 841,
    name: 'گراب سفلی',
    value: 'گراب-سفلی',
    province_id: 23,
  },
  {
    id: 842,
    name: 'لنده',
    value: 'لنده',
    province_id: 23,
  },
  {
    id: 843,
    name: 'لیکک',
    value: 'لیکک',
    province_id: 23,
  },
  {
    id: 844,
    name: 'مادوان',
    value: 'مادوان',
    province_id: 23,
  },
  {
    id: 845,
    name: 'مارگون',
    value: 'مارگون',
    province_id: 23,
  },
  {
    id: 846,
    name: 'یاسوج',
    value: 'یاسوج',
    province_id: 23,
  },
  {
    id: 847,
    name: 'انبارآلوم',
    value: 'انبارآلوم',
    province_id: 24,
  },
  {
    id: 848,
    name: 'اینچه برون',
    value: 'اینچه-برون',
    province_id: 24,
  },
  {
    id: 849,
    name: 'آزادشهر',
    value: 'آزادشهر',
    province_id: 24,
  },
  {
    id: 850,
    name: 'آق قلا',
    value: 'آق-قلا',
    province_id: 24,
  },
  {
    id: 851,
    name: 'بندرترکمن',
    value: 'بندرترکمن',
    province_id: 24,
  },
  {
    id: 852,
    name: 'بندرگز',
    value: 'بندرگز',
    province_id: 24,
  },
  {
    id: 853,
    name: 'جلین',
    value: 'جلین',
    province_id: 24,
  },
  {
    id: 854,
    name: 'خان ببین',
    value: 'خان-ببین',
    province_id: 24,
  },
  {
    id: 855,
    name: 'دلند',
    value: 'دلند',
    province_id: 24,
  },
  {
    id: 856,
    name: 'رامیان',
    value: 'رامیان',
    province_id: 24,
  },
  {
    id: 857,
    name: 'سرخنکلاته',
    value: 'سرخنکلاته',
    province_id: 24,
  },
  {
    id: 858,
    name: 'سیمین شهر',
    value: 'سیمین-شهر',
    province_id: 24,
  },
  {
    id: 859,
    name: 'علی آباد کتول',
    value: 'علی-آباد-کتول',
    province_id: 24,
  },
  {
    id: 860,
    name: 'فاضل آباد',
    value: 'فاضل-آباد',
    province_id: 24,
  },
  {
    id: 861,
    name: 'کردکوی',
    value: 'کردکوی',
    province_id: 24,
  },
  {
    id: 862,
    name: 'کلاله',
    value: 'کلاله',
    province_id: 24,
  },
  {
    id: 863,
    name: 'گالیکش',
    value: 'گالیکش',
    province_id: 24,
  },
  {
    id: 864,
    name: 'گرگان',
    value: 'گرگان',
    province_id: 24,
  },
  {
    id: 865,
    name: 'گمیش تپه',
    value: 'گمیش-تپه',
    province_id: 24,
  },
  {
    id: 866,
    name: 'گنبدکاووس',
    value: 'گنبدکاووس',
    province_id: 24,
  },
  {
    id: 867,
    name: 'مراوه',
    value: 'مراوه',
    province_id: 24,
  },
  {
    id: 868,
    name: 'مینودشت',
    value: 'مینودشت',
    province_id: 24,
  },
  {
    id: 869,
    name: 'نگین شهر',
    value: 'نگین-شهر',
    province_id: 24,
  },
  {
    id: 870,
    name: 'نوده خاندوز',
    value: 'نوده-خاندوز',
    province_id: 24,
  },
  {
    id: 871,
    name: 'نوکنده',
    value: 'نوکنده',
    province_id: 24,
  },
  {
    id: 872,
    name: 'ازنا',
    value: 'ازنا',
    province_id: 25,
  },
  {
    id: 873,
    name: 'اشترینان',
    value: 'اشترینان',
    province_id: 25,
  },
  {
    id: 874,
    name: 'الشتر',
    value: 'الشتر',
    province_id: 25,
  },
  {
    id: 875,
    name: 'الیگودرز',
    value: 'الیگودرز',
    province_id: 25,
  },
  {
    id: 876,
    name: 'بروجرد',
    value: 'بروجرد',
    province_id: 25,
  },
  {
    id: 877,
    name: 'پلدختر',
    value: 'پلدختر',
    province_id: 25,
  },
  {
    id: 878,
    name: 'چالانچولان',
    value: 'چالانچولان',
    province_id: 25,
  },
  {
    id: 879,
    name: 'چغلوندی',
    value: 'چغلوندی',
    province_id: 25,
  },
  {
    id: 880,
    name: 'چقابل',
    value: 'چقابل',
    province_id: 25,
  },
  {
    id: 881,
    name: 'خرم آباد',
    value: 'لرستان-خرم-آباد',
    province_id: 25,
  },
  {
    id: 882,
    name: 'درب گنبد',
    value: 'درب-گنبد',
    province_id: 25,
  },
  {
    id: 883,
    name: 'دورود',
    value: 'دورود',
    province_id: 25,
  },
  {
    id: 884,
    name: 'زاغه',
    value: 'زاغه',
    province_id: 25,
  },
  {
    id: 885,
    name: 'سپیددشت',
    value: 'سپیددشت',
    province_id: 25,
  },
  {
    id: 886,
    name: 'سراب دوره',
    value: 'سراب-دوره',
    province_id: 25,
  },
  {
    id: 887,
    name: 'فیروزآباد',
    value: 'لرستان-فیروزآباد',
    province_id: 25,
  },
  {
    id: 888,
    name: 'کونانی',
    value: 'کونانی',
    province_id: 25,
  },
  {
    id: 889,
    name: 'کوهدشت',
    value: 'کوهدشت',
    province_id: 25,
  },
  {
    id: 890,
    name: 'گراب',
    value: 'گراب',
    province_id: 25,
  },
  {
    id: 891,
    name: 'معمولان',
    value: 'معمولان',
    province_id: 25,
  },
  {
    id: 892,
    name: 'مومن آباد',
    value: 'مومن-آباد',
    province_id: 25,
  },
  {
    id: 893,
    name: 'نورآباد',
    value: 'لرستان-نورآباد',
    province_id: 25,
  },
  {
    id: 894,
    name: 'ویسیان',
    value: 'ویسیان',
    province_id: 25,
  },
  {
    id: 895,
    name: 'احمدسرگوراب',
    value: 'احمدسرگوراب',
    province_id: 26,
  },
  {
    id: 896,
    name: 'اسالم',
    value: 'اسالم',
    province_id: 26,
  },
  {
    id: 897,
    name: 'اطاقور',
    value: 'اطاقور',
    province_id: 26,
  },
  {
    id: 898,
    name: 'املش',
    value: 'املش',
    province_id: 26,
  },
  {
    id: 899,
    name: 'آستارا',
    value: 'آستارا',
    province_id: 26,
  },
  {
    id: 900,
    name: 'آستانه اشرفیه',
    value: 'آستانه-اشرفیه',
    province_id: 26,
  },
  {
    id: 901,
    name: 'بازار جمعه',
    value: 'بازار-جمعه',
    province_id: 26,
  },
  {
    id: 902,
    name: 'بره سر',
    value: 'بره-سر',
    province_id: 26,
  },
  {
    id: 903,
    name: 'بندرانزلی',
    value: 'بندرانزلی',
    province_id: 26,
  },
  {
    id: 906,
    name: 'پره سر',
    value: 'پره-سر',
    province_id: 26,
  },
  {
    id: 907,
    name: 'تالش',
    value: 'تالش',
    province_id: 26,
  },
  {
    id: 908,
    name: 'توتکابن',
    value: 'توتکابن',
    province_id: 26,
  },
  {
    id: 909,
    name: 'جیرنده',
    value: 'جیرنده',
    province_id: 26,
  },
  {
    id: 910,
    name: 'چابکسر',
    value: 'چابکسر',
    province_id: 26,
  },
  {
    id: 911,
    name: 'چاف و چمخاله',
    value: 'چاف-و-چمخاله',
    province_id: 26,
  },
  {
    id: 912,
    name: 'چوبر',
    value: 'چوبر',
    province_id: 26,
  },
  {
    id: 913,
    name: 'حویق',
    value: 'حویق',
    province_id: 26,
  },
  {
    id: 914,
    name: 'خشکبیجار',
    value: 'خشکبیجار',
    province_id: 26,
  },
  {
    id: 915,
    name: 'خمام',
    value: 'خمام',
    province_id: 26,
  },
  {
    id: 916,
    name: 'دیلمان',
    value: 'دیلمان',
    province_id: 26,
  },
  {
    id: 917,
    name: 'رانکوه',
    value: 'رانکوه',
    province_id: 26,
  },
  {
    id: 918,
    name: 'رحیم آباد',
    value: 'رحیم-آباد',
    province_id: 26,
  },
  {
    id: 919,
    name: 'رستم آباد',
    value: 'رستم-آباد',
    province_id: 26,
  },
  {
    id: 920,
    name: 'رشت',
    value: 'رشت',
    province_id: 26,
  },
  {
    id: 921,
    name: 'رضوانشهر',
    value: 'گیلان-رضوانشهر',
    province_id: 26,
  },
  {
    id: 922,
    name: 'رودبار',
    value: 'گیلان-رودبار',
    province_id: 26,
  },
  {
    id: 923,
    name: 'رودبنه',
    value: 'رودبنه',
    province_id: 26,
  },
  {
    id: 924,
    name: 'رودسر',
    value: 'رودسر',
    province_id: 26,
  },
  {
    id: 925,
    name: 'سنگر',
    value: 'سنگر',
    province_id: 26,
  },
  {
    id: 926,
    name: 'سیاهکل',
    value: 'سیاهکل',
    province_id: 26,
  },
  {
    id: 927,
    name: 'شفت',
    value: 'شفت',
    province_id: 26,
  },
  {
    id: 928,
    name: 'شلمان',
    value: 'شلمان',
    province_id: 26,
  },
  {
    id: 929,
    name: 'صومعه سرا',
    value: 'صومعه-سرا',
    province_id: 26,
  },
  {
    id: 930,
    name: 'فومن',
    value: 'فومن',
    province_id: 26,
  },
  {
    id: 931,
    name: 'کلاچای',
    value: 'کلاچای',
    province_id: 26,
  },
  {
    id: 932,
    name: 'کوچصفهان',
    value: 'کوچصفهان',
    province_id: 26,
  },
  {
    id: 933,
    name: 'کومله',
    value: 'کومله',
    province_id: 26,
  },
  {
    id: 934,
    name: 'کیاشهر',
    value: 'کیاشهر',
    province_id: 26,
  },
  {
    id: 935,
    name: 'گوراب زرمیخ',
    value: 'گوراب-زرمیخ',
    province_id: 26,
  },
  {
    id: 936,
    name: 'لاهیجان',
    value: 'لاهیجان',
    province_id: 26,
  },
  {
    id: 937,
    name: 'لشت نشا',
    value: 'لشت-نشا',
    province_id: 26,
  },
  {
    id: 938,
    name: 'لنگرود',
    value: 'لنگرود',
    province_id: 26,
  },
  {
    id: 939,
    name: 'لوشان',
    value: 'لوشان',
    province_id: 26,
  },
  {
    id: 940,
    name: 'لولمان',
    value: 'لولمان',
    province_id: 26,
  },
  {
    id: 941,
    name: 'لوندویل',
    value: 'لوندویل',
    province_id: 26,
  },
  {
    id: 942,
    name: 'لیسار',
    value: 'لیسار',
    province_id: 26,
  },
  {
    id: 943,
    name: 'ماسال',
    value: 'ماسال',
    province_id: 26,
  },
  {
    id: 944,
    name: 'ماسوله',
    value: 'ماسوله',
    province_id: 26,
  },
  {
    id: 945,
    name: 'مرجقل',
    value: 'مرجقل',
    province_id: 26,
  },
  {
    id: 946,
    name: 'منجیل',
    value: 'منجیل',
    province_id: 26,
  },
  {
    id: 947,
    name: 'واجارگاه',
    value: 'واجارگاه',
    province_id: 26,
  },
  {
    id: 948,
    name: 'امیرکلا',
    value: 'امیرکلا',
    province_id: 27,
  },
  {
    id: 949,
    name: 'ایزدشهر',
    value: 'ایزدشهر',
    province_id: 27,
  },
  {
    id: 950,
    name: 'آلاشت',
    value: 'آلاشت',
    province_id: 27,
  },
  {
    id: 951,
    name: 'آمل',
    value: 'آمل',
    province_id: 27,
  },
  {
    id: 952,
    name: 'بابل',
    value: 'بابل',
    province_id: 27,
  },
  {
    id: 953,
    name: 'بابلسر',
    value: 'بابلسر',
    province_id: 27,
  },
  {
    id: 954,
    name: 'بلده',
    value: 'مازندران-بلده',
    province_id: 27,
  },
  {
    id: 955,
    name: 'بهشهر',
    value: 'بهشهر',
    province_id: 27,
  },
  {
    id: 956,
    name: 'بهنمیر',
    value: 'بهنمیر',
    province_id: 27,
  },
  {
    id: 957,
    name: 'پل سفید',
    value: 'پل-سفید',
    province_id: 27,
  },
  {
    id: 958,
    name: 'تنکابن',
    value: 'تنکابن',
    province_id: 27,
  },
  {
    id: 959,
    name: 'جویبار',
    value: 'جویبار',
    province_id: 27,
  },
  {
    id: 960,
    name: 'چالوس',
    value: 'چالوس',
    province_id: 27,
  },
  {
    id: 961,
    name: 'چمستان',
    value: 'چمستان',
    province_id: 27,
  },
  {
    id: 962,
    name: 'خرم آباد',
    value: 'مازندران-خرم-آباد',
    province_id: 27,
  },
  {
    id: 963,
    name: 'خلیل شهر',
    value: 'خلیل-شهر',
    province_id: 27,
  },
  {
    id: 964,
    name: 'خوش رودپی',
    value: 'خوش-رودپی',
    province_id: 27,
  },
  {
    id: 965,
    name: 'دابودشت',
    value: 'دابودشت',
    province_id: 27,
  },
  {
    id: 966,
    name: 'رامسر',
    value: 'رامسر',
    province_id: 27,
  },
  {
    id: 967,
    name: 'رستمکلا',
    value: 'رستمکلا',
    province_id: 27,
  },
  {
    id: 968,
    name: 'رویان',
    value: 'رویان',
    province_id: 27,
  },
  {
    id: 969,
    name: 'رینه',
    value: 'رینه',
    province_id: 27,
  },
  {
    id: 970,
    name: 'زرگرمحله',
    value: 'زرگرمحله',
    province_id: 27,
  },
  {
    id: 971,
    name: 'زیرآب',
    value: 'زیرآب',
    province_id: 27,
  },
  {
    id: 972,
    name: 'ساری',
    value: 'ساری',
    province_id: 27,
  },
  {
    id: 973,
    name: 'سرخرود',
    value: 'سرخرود',
    province_id: 27,
  },
  {
    id: 974,
    name: 'سلمان شهر',
    value: 'سلمان-شهر',
    province_id: 27,
  },
  {
    id: 975,
    name: 'سورک',
    value: 'سورک',
    province_id: 27,
  },
  {
    id: 976,
    name: 'شیرگاه',
    value: 'شیرگاه',
    province_id: 27,
  },
  {
    id: 977,
    name: 'شیرود',
    value: 'شیرود',
    province_id: 27,
  },
  {
    id: 978,
    name: 'عباس آباد',
    value: 'عباس-آباد',
    province_id: 27,
  },
  {
    id: 979,
    name: 'فریدونکنار',
    value: 'فریدونکنار',
    province_id: 27,
  },
  {
    id: 980,
    name: 'فریم',
    value: 'فریم',
    province_id: 27,
  },
  {
    id: 981,
    name: 'قائم شهر',
    value: 'قائم-شهر',
    province_id: 27,
  },
  {
    id: 982,
    name: 'کتالم',
    value: 'کتالم',
    province_id: 27,
  },
  {
    id: 983,
    name: 'کلارآباد',
    value: 'کلارآباد',
    province_id: 27,
  },
  {
    id: 984,
    name: 'کلاردشت',
    value: 'کلاردشت',
    province_id: 27,
  },
  {
    id: 985,
    name: 'کله بست',
    value: 'کله-بست',
    province_id: 27,
  },
  {
    id: 986,
    name: 'کوهی خیل',
    value: 'کوهی-خیل',
    province_id: 27,
  },
  {
    id: 987,
    name: 'کیاسر',
    value: 'کیاسر',
    province_id: 27,
  },
  {
    id: 988,
    name: 'کیاکلا',
    value: 'کیاکلا',
    province_id: 27,
  },
  {
    id: 989,
    name: 'گتاب',
    value: 'گتاب',
    province_id: 27,
  },
  {
    id: 990,
    name: 'گزنک',
    value: 'گزنک',
    province_id: 27,
  },
  {
    id: 991,
    name: 'گلوگاه',
    value: 'گلوگاه',
    province_id: 27,
  },
  {
    id: 992,
    name: 'محمودآباد',
    value: 'مازندران-محمودآباد',
    province_id: 27,
  },
  {
    id: 993,
    name: 'مرزن آباد',
    value: 'مرزن-آباد',
    province_id: 27,
  },
  {
    id: 994,
    name: 'مرزیکلا',
    value: 'مرزیکلا',
    province_id: 27,
  },
  {
    id: 995,
    name: 'نشتارود',
    value: 'نشتارود',
    province_id: 27,
  },
  {
    id: 996,
    name: 'نکا',
    value: 'نکا',
    province_id: 27,
  },
  {
    id: 997,
    name: 'نور',
    value: 'نور',
    province_id: 27,
  },
  {
    id: 998,
    name: 'نوشهر',
    value: 'نوشهر',
    province_id: 27,
  },
  {
    id: 999,
    name: 'اراک',
    value: 'اراک',
    province_id: 28,
  },
  {
    id: 1000,
    name: 'آستانه',
    value: 'آستانه',
    province_id: 28,
  },
  {
    id: 1001,
    name: 'آشتیان',
    value: 'آشتیان',
    province_id: 28,
  },
  {
    id: 1002,
    name: 'پرندک',
    value: 'پرندک',
    province_id: 28,
  },
  {
    id: 1003,
    name: 'تفرش',
    value: 'تفرش',
    province_id: 28,
  },
  {
    id: 1004,
    name: 'توره',
    value: 'توره',
    province_id: 28,
  },
  {
    id: 1005,
    name: 'جاورسیان',
    value: 'جاورسیان',
    province_id: 28,
  },
  {
    id: 1006,
    name: 'خشکرود',
    value: 'خشکرود',
    province_id: 28,
  },
  {
    id: 1007,
    name: 'خمین',
    value: 'خمین',
    province_id: 28,
  },
  {
    id: 1008,
    name: 'خنداب',
    value: 'خنداب',
    province_id: 28,
  },
  {
    id: 1009,
    name: 'داودآباد',
    value: 'داودآباد',
    province_id: 28,
  },
  {
    id: 1010,
    name: 'دلیجان',
    value: 'دلیجان',
    province_id: 28,
  },
  {
    id: 1011,
    name: 'رازقان',
    value: 'رازقان',
    province_id: 28,
  },
  {
    id: 1012,
    name: 'زاویه',
    value: 'زاویه',
    province_id: 28,
  },
  {
    id: 1013,
    name: 'ساروق',
    value: 'ساروق',
    province_id: 28,
  },
  {
    id: 1014,
    name: 'ساوه',
    value: 'ساوه',
    province_id: 28,
  },
  {
    id: 1015,
    name: 'سنجان',
    value: 'سنجان',
    province_id: 28,
  },
  {
    id: 1016,
    name: 'شازند',
    value: 'شازند',
    province_id: 28,
  },
  {
    id: 1017,
    name: 'غرق آباد',
    value: 'غرق-آباد',
    province_id: 28,
  },
  {
    id: 1018,
    name: 'فرمهین',
    value: 'فرمهین',
    province_id: 28,
  },
  {
    id: 1019,
    name: 'قورچی باشی',
    value: 'قورچی-باشی',
    province_id: 28,
  },
  {
    id: 1020,
    name: 'کرهرود',
    value: 'کرهرود',
    province_id: 28,
  },
  {
    id: 1021,
    name: 'کمیجان',
    value: 'کمیجان',
    province_id: 28,
  },
  {
    id: 1022,
    name: 'مامونیه',
    value: 'مامونیه',
    province_id: 28,
  },
  {
    id: 1023,
    name: 'محلات',
    value: 'محلات',
    province_id: 28,
  },
  {
    id: 1024,
    name: 'مهاجران',
    value: 'مهاجران',
    province_id: 28,
  },
  {
    id: 1025,
    name: 'میلاجرد',
    value: 'میلاجرد',
    province_id: 28,
  },
  {
    id: 1026,
    name: 'نراق',
    value: 'نراق',
    province_id: 28,
  },
  {
    id: 1027,
    name: 'نوبران',
    value: 'نوبران',
    province_id: 28,
  },
  {
    id: 1028,
    name: 'نیمور',
    value: 'نیمور',
    province_id: 28,
  },
  {
    id: 1029,
    name: 'هندودر',
    value: 'هندودر',
    province_id: 28,
  },
  {
    id: 1030,
    name: 'ابوموسی',
    value: 'ابوموسی',
    province_id: 29,
  },
  {
    id: 1031,
    name: 'بستک',
    value: 'بستک',
    province_id: 29,
  },
  {
    id: 1032,
    name: 'بندرجاسک',
    value: 'بندرجاسک',
    province_id: 29,
  },
  {
    id: 1033,
    name: 'بندرچارک',
    value: 'بندرچارک',
    province_id: 29,
  },
  {
    id: 1034,
    name: 'بندرخمیر',
    value: 'بندرخمیر',
    province_id: 29,
  },
  {
    id: 1035,
    name: 'بندرعباس',
    value: 'بندرعباس',
    province_id: 29,
  },
  {
    id: 1036,
    name: 'بندرلنگه',
    value: 'بندرلنگه',
    province_id: 29,
  },
  {
    id: 1037,
    name: 'بیکا',
    value: 'بیکا',
    province_id: 29,
  },
  {
    id: 1038,
    name: 'پارسیان',
    value: 'پارسیان',
    province_id: 29,
  },
  {
    id: 1039,
    name: 'تخت',
    value: 'تخت',
    province_id: 29,
  },
  {
    id: 1040,
    name: 'جناح',
    value: 'جناح',
    province_id: 29,
  },
  {
    id: 1041,
    name: 'حاجی آباد',
    value: 'هرمزگان-حاجی-آباد',
    province_id: 29,
  },
  {
    id: 1042,
    name: 'درگهان',
    value: 'درگهان',
    province_id: 29,
  },
  {
    id: 1043,
    name: 'دهبارز',
    value: 'دهبارز',
    province_id: 29,
  },
  {
    id: 1044,
    name: 'رویدر',
    value: 'رویدر',
    province_id: 29,
  },
  {
    id: 1045,
    name: 'زیارتعلی',
    value: 'زیارتعلی',
    province_id: 29,
  },
  {
    id: 1046,
    name: 'سردشت',
    value: 'هرمزگان-سردشت',
    province_id: 29,
  },
  {
    id: 1047,
    name: 'سندرک',
    value: 'سندرک',
    province_id: 29,
  },
  {
    id: 1048,
    name: 'سوزا',
    value: 'سوزا',
    province_id: 29,
  },
  {
    id: 1049,
    name: 'سیریک',
    value: 'سیریک',
    province_id: 29,
  },
  {
    id: 1050,
    name: 'فارغان',
    value: 'فارغان',
    province_id: 29,
  },
  {
    id: 1051,
    name: 'فین',
    value: 'فین',
    province_id: 29,
  },
  {
    id: 1052,
    name: 'قشم',
    value: 'قشم',
    province_id: 29,
  },
  {
    id: 1053,
    name: 'قلعه قاضی',
    value: 'قلعه-قاضی',
    province_id: 29,
  },
  {
    id: 1054,
    name: 'کنگ',
    value: 'کنگ',
    province_id: 29,
  },
  {
    id: 1055,
    name: 'کوشکنار',
    value: 'کوشکنار',
    province_id: 29,
  },
  {
    id: 1056,
    name: 'کیش',
    value: 'کیش',
    province_id: 29,
  },
  {
    id: 1057,
    name: 'گوهران',
    value: 'گوهران',
    province_id: 29,
  },
  {
    id: 1058,
    name: 'میناب',
    value: 'میناب',
    province_id: 29,
  },
  {
    id: 1059,
    name: 'هرمز',
    value: 'هرمز',
    province_id: 29,
  },
  {
    id: 1060,
    name: 'هشتبندی',
    value: 'هشتبندی',
    province_id: 29,
  },
  {
    id: 1061,
    name: 'ازندریان',
    value: 'ازندریان',
    province_id: 30,
  },
  {
    id: 1062,
    name: 'اسدآباد',
    value: 'اسدآباد',
    province_id: 30,
  },
  {
    id: 1063,
    name: 'برزول',
    value: 'برزول',
    province_id: 30,
  },
  {
    id: 1064,
    name: 'بهار',
    value: 'بهار',
    province_id: 30,
  },
  {
    id: 1065,
    name: 'تویسرکان',
    value: 'تویسرکان',
    province_id: 30,
  },
  {
    id: 1066,
    name: 'جورقان',
    value: 'جورقان',
    province_id: 30,
  },
  {
    id: 1067,
    name: 'جوکار',
    value: 'جوکار',
    province_id: 30,
  },
  {
    id: 1068,
    name: 'دمق',
    value: 'دمق',
    province_id: 30,
  },
  {
    id: 1069,
    name: 'رزن',
    value: 'رزن',
    province_id: 30,
  },
  {
    id: 1070,
    name: 'زنگنه',
    value: 'زنگنه',
    province_id: 30,
  },
  {
    id: 1071,
    name: 'سامن',
    value: 'سامن',
    province_id: 30,
  },
  {
    id: 1072,
    name: 'سرکان',
    value: 'سرکان',
    province_id: 30,
  },
  {
    id: 1073,
    name: 'شیرین سو',
    value: 'شیرین-سو',
    province_id: 30,
  },
  {
    id: 1074,
    name: 'صالح آباد',
    value: 'همدان-صالح-آباد',
    province_id: 30,
  },
  {
    id: 1075,
    name: 'فامنین',
    value: 'فامنین',
    province_id: 30,
  },
  {
    id: 1076,
    name: 'فرسفج',
    value: 'فرسفج',
    province_id: 30,
  },
  {
    id: 1077,
    name: 'فیروزان',
    value: 'فیروزان',
    province_id: 30,
  },
  {
    id: 1078,
    name: 'قروه درجزین',
    value: 'قروه-درجزین',
    province_id: 30,
  },
  {
    id: 1079,
    name: 'قهاوند',
    value: 'قهاوند',
    province_id: 30,
  },
  {
    id: 1080,
    name: 'کبودر آهنگ',
    value: 'کبودر-آهنگ',
    province_id: 30,
  },
  {
    id: 1081,
    name: 'گل تپه',
    value: 'گل-تپه',
    province_id: 30,
  },
  {
    id: 1082,
    name: 'گیان',
    value: 'گیان',
    province_id: 30,
  },
  {
    id: 1083,
    name: 'لالجین',
    value: 'لالجین',
    province_id: 30,
  },
  {
    id: 1084,
    name: 'مریانج',
    value: 'مریانج',
    province_id: 30,
  },
  {
    id: 1085,
    name: 'ملایر',
    value: 'ملایر',
    province_id: 30,
  },
  {
    id: 1086,
    name: 'نهاوند',
    value: 'نهاوند',
    province_id: 30,
  },
  {
    id: 1087,
    name: 'همدان',
    value: 'همدان',
    province_id: 30,
  },
  {
    id: 1088,
    name: 'ابرکوه',
    value: 'ابرکوه',
    province_id: 31,
  },
  {
    id: 1089,
    name: 'احمدآباد',
    value: 'احمدآباد',
    province_id: 31,
  },
  {
    id: 1090,
    name: 'اردکان',
    value: 'یزد-اردکان',
    province_id: 31,
  },
  {
    id: 1091,
    name: 'اشکذر',
    value: 'اشکذر',
    province_id: 31,
  },
  {
    id: 1092,
    name: 'بافق',
    value: 'بافق',
    province_id: 31,
  },
  {
    id: 1093,
    name: 'بفروئیه',
    value: 'بفروئیه',
    province_id: 31,
  },
  {
    id: 1094,
    name: 'بهاباد',
    value: 'بهاباد',
    province_id: 31,
  },
  {
    id: 1095,
    name: 'تفت',
    value: 'تفت',
    province_id: 31,
  },
  {
    id: 1096,
    name: 'حمیدیا',
    value: 'حمیدیا',
    province_id: 31,
  },
  {
    id: 1097,
    name: 'خضرآباد',
    value: 'خضرآباد',
    province_id: 31,
  },
  {
    id: 1098,
    name: 'دیهوک',
    value: 'دیهوک',
    province_id: 31,
  },
  {
    id: 1099,
    name: 'زارچ',
    value: 'زارچ',
    province_id: 31,
  },
  {
    id: 1100,
    name: 'شاهدیه',
    value: 'شاهدیه',
    province_id: 31,
  },
  {
    id: 1101,
    name: 'طبس',
    value: 'یزد-طبس',
    province_id: 31,
  },
  {
    id: 1103,
    name: 'عقدا',
    value: 'عقدا',
    province_id: 31,
  },
  {
    id: 1104,
    name: 'مروست',
    value: 'مروست',
    province_id: 31,
  },
  {
    id: 1105,
    name: 'مهردشت',
    value: 'مهردشت',
    province_id: 31,
  },
  {
    id: 1106,
    name: 'مهریز',
    value: 'مهریز',
    province_id: 31,
  },
  {
    id: 1107,
    name: 'میبد',
    value: 'میبد',
    province_id: 31,
  },
  {
    id: 1108,
    name: 'ندوشن',
    value: 'ندوشن',
    province_id: 31,
  },
  {
    id: 1109,
    name: 'نیر',
    value: 'یزد-نیر',
    province_id: 31,
  },
  {
    id: 1110,
    name: 'هرات',
    value: 'هرات',
    province_id: 31,
  },
  {
    id: 1111,
    name: 'یزد',
    value: 'یزد',
    province_id: 31,
  },
  {
    id: 1116,
    name: 'پرند',
    value: 'پرند',
    province_id: 8,
  },
  {
    id: 1117,
    name: 'فردیس',
    value: 'فردیس',
    province_id: 5,
  },
  {
    id: 1118,
    name: 'مارلیک',
    value: 'مارلیک',
    province_id: 5,
  },
  {
    id: 1119,
    name: 'سادات شهر',
    value: 'سادات-شهر',
    province_id: 27,
  },
  {
    id: 1121,
    name: 'زیباکنار',
    value: 'زیباکنار',
    province_id: 26,
  },
  {
    id: 1135,
    name: 'کردان',
    value: 'کردان',
    province_id: 5,
  },
  {
    id: 1137,
    name: 'ساوجبلاغ',
    value: 'ساوجبلاغ',
    province_id: 5,
  },
  {
    id: 1138,
    name: 'تهران دشت',
    value: 'تهران-دشت',
    province_id: 5,
  },
  {
    id: 1150,
    name: 'گلبهار',
    value: 'گلبهار',
    province_id: 11,
  },
  {
    id: 1153,
    name: 'قیامدشت',
    value: 'قیامدشت',
    province_id: 8,
  },
  {
    id: 1155,
    name: 'بینالود',
    value: 'بینالود',
    province_id: 11,
  },
  {
    id: 1159,
    name: 'پیربازار',
    value: 'پیربازار',
    province_id: 26,
  },
  {
    id: 1160,
    name: 'رضوانشهر',
    value: 'رضوانشهر',
    province_id: 31,
  },
]
