export const countryData = [
  { name: 'Afghanistan', value: 'AF', label: 'افغانستان' },
  { name: 'land Islands', value: 'AX', label: 'جزایر الند' },
  { name: 'Albania', value: 'AL', label: 'آلبانی' },
  { name: 'Algeria', value: 'DZ', label: 'الجزایر' },
  { name: 'American Samoa', value: 'AS', label: 'ساموآی آمریکا' },
  { name: 'AndorrA', value: 'AD', label: 'آندورا' },
  { name: 'Angola', value: 'AO', label: 'آنگولا' },
  { name: 'Anguilla', value: 'AI', label: 'آنگویلا' },
  { name: 'Antigua and Barbuda', value: 'AG', label: 'آنتیگوآ و باربودا' },
  { name: 'Argentina', value: 'AR', label: 'آرژانتین' },
  { name: 'Armenia', value: 'AM', label: 'ارمنستان' },
  { name: 'Aruba', value: 'AW', label: 'آروبا' },
  { name: 'Australia', value: 'AU', label: 'استرالیا' },
  { name: 'Austria', value: 'AT', label: 'اتریش' },
  { name: 'Azerbaijan', value: 'AZ', label: 'آذربایجان' },
  { name: 'Bahamas', value: 'BS', label: 'باهاما' },
  { name: 'Bahrain', value: 'BH', label: 'بحرین' },
  { name: 'Bangladesh', value: 'BD', label: 'بنگلادش' },
  { name: 'Barbados', value: 'BB', label: 'باربادوس' },
  { name: 'Belarus', value: 'BY', label: 'بلاروس' },
  { name: 'Belgium', value: 'BE', label: 'بلژیک' },
  { name: 'Belize', value: 'BZ', label: 'بلیز' },
  { name: 'Benin', value: 'BJ', label: 'بنین' },
  { name: 'Bermuda', value: 'BM', label: 'برمودا' },
  { name: 'Bhutan', value: 'BT', label: 'بوتان' },
  { name: 'Bolivia', value: 'BO', label: 'بولیوی' },
  { name: 'Bosnia and Herzegovina', value: 'BA', label: 'بوسنی و هرزگوین' },
  { name: 'Botswana', value: 'BW', label: 'بوتسوانا' },
  { name: 'Bouvet Island', value: 'BV', label: 'جزیره بووه' },
  { name: 'Brazil', value: 'BR', label: 'برزیل' },
  { name: 'Brunei Darussalam', value: 'BN', label: 'برونئی' },
  { name: 'Bulgaria', value: 'BG', label: 'بلغارستان' },
  { name: 'Burkina Faso', value: 'BF', label: 'بورکینافاسو' },
  { name: 'Burundi', value: 'BI', label: 'بوروندی' },
  { name: 'Cambodia', value: 'KH', label: 'کامبوج' },
  { name: 'Cameroon', value: 'CM', label: 'کامرون' },
  { name: 'Canada', value: 'CA', label: 'کانادا' },
  { name: 'Cape Verde', value: 'CV', label: 'کیپ ورد' },
  { name: 'Cayman Islands', value: 'KY', label: 'جزایر کیمن' },
  { name: 'Central African Republic', value: 'CF', label: 'جمهوری آفریقای مرکزی' },
  { name: 'Chad', value: 'TD', label: 'چاد' },
  { name: 'Chile', value: 'CL', label: 'شیلی' },
  { name: 'China', value: 'CN', label: 'چین' },
  { name: 'Christmas Island', value: 'CX', label: 'جزایر کریسمس' },
  { name: 'Colombia', value: 'CO', label: 'کلمبیا' },
  { name: 'Comoros', value: 'KM', label: 'اتحاد قمر' },
  { name: 'Congo', value: 'CG', label: 'کنگو' },
  { name: 'Congo, The Democratic Republic of the', value: 'CD', label: 'جمهوری دموکراتیک کنگو' },
  { name: 'Cook Islands', value: 'CK', label: 'جزایر کوک' },
  { name: 'Costa Rica', value: 'CR', label: 'کاستاریکا' },
  { name: 'Croatia', value: 'HR', label: 'کرواسی' },
  { name: 'Cuba', value: 'CU', label: 'کوبا' },
  { name: 'Cyprus', value: 'CY', label: 'قبرس' },
  { name: 'Czech Republic', value: 'CZ', label: 'جمهوری چک' },
  { name: 'Denmark', value: 'DK', label: 'دانمارک' },
  { name: 'Djibouti', value: 'DJ', label: 'جیبوتی' },
  { name: 'Dominica', value: 'DM', label: 'دومینیکا' },
  { name: 'Dominican Republic', value: 'DO', label: 'جمهوری دومینیکن' },
  { name: 'Ecuador', value: 'EC', label: 'اکوادور' },
  { name: 'Egypt', value: 'EG', label: 'مصر' },
  { name: 'El Salvador', value: 'SV', label: 'السالوادور' },
  { name: 'Equatorial Guinea', value: 'GQ', label: 'گینه استوایی' },
  { name: 'Eritrea', value: 'ER', label: 'اریتره' },
  { name: 'Estonia', value: 'EE', label: 'استونی' },
  { name: 'Ethiopia', value: 'ET', label: 'اتیوپی' },
  { name: 'Falkland Islands (Malvinas)', value: 'FK', label: 'جزایر فالکلند' },
  { name: 'Faroe Islands', value: 'FO', label: 'جزایر فارو' },
  { name: 'Fiji', value: 'FJ', label: 'فیجی' },
  { name: 'Finland', value: 'FI', label: 'فنلاند' },
  { name: 'France', value: 'FR', label: 'فرانسه' },
  { name: 'French Guiana', value: 'GF', label: 'گویان فرانسه' },
  { name: 'French Polynesia', value: 'PF', label: 'پولینزی فرانسوی' },
  { name: 'Gabon', value: 'GA', label: 'گابن' },
  { name: 'Gambia', value: 'GM', label: 'گامیا' },
  { name: 'Georgia', value: 'GE', label: 'گرجستان' },
  { name: 'Germany', value: 'DE', label: 'آلمان' },
  { name: 'Ghana', value: 'GH', label: 'غنا' },
  { name: 'Greece', value: 'GR', label: 'یونان' },
  { name: 'Greenland', value: 'GL', label: 'گرینلند' },
  { name: 'Grenada', value: 'GD', label: 'گرانادا' },
  { name: 'Guam', value: 'GU', label: 'گوام' },
  { name: 'Guatemala', value: 'GT', label: 'گواتمالا' },
  { name: 'Guinea', value: 'GN', label: 'گینه' },
  { name: 'Guinea-Bissau', value: 'GW', label: 'گینه بیسائو' },
  { name: 'Guyana', value: 'GY', label: 'گویان' },
  { name: 'Haiti', value: 'HT', label: 'هاییتی' },
  { name: 'Honduras', value: 'HN', label: 'هندوراس' },
  { name: 'Hong Kong', value: 'HK', label: 'هنگ‌کنگ' },
  { name: 'Hungary', value: 'HU', label: 'مجارستان' },
  { name: 'Iceland', value: 'IS', label: 'ایسلند' },
  { name: 'India', value: 'IN', label: 'هند' },
  { name: 'Indonesia', value: 'ID', label: 'اندونزی' },
  { name: 'Iraq', value: 'IQ', label: 'عراق' },
  { name: 'Ireland', value: 'IE', label: 'ایرلند' },
  { name: 'Israel', value: 'IL', label: 'اسراییل' },
  { name: 'Italy', value: 'IT', label: 'ایتالیا' },
  { name: 'Jamaica', value: 'JM', label: 'جاماییکا' },
  { name: 'Japan', value: 'JP', label: 'ژاپن' },
  { name: 'Jordan', value: 'JO', label: 'اردن' },
  { name: 'Kazakhstan', value: 'KZ', label: 'قزاقستان' },
  { name: 'Kenya', value: 'KE', label: 'کنیا' },
  { name: "Korea, Democratic People'S Republic of", value: 'KP', label: 'کره شمالی' },
  { name: 'Korea, Republic of', value: 'KR', label: 'کره جنوبی' },
  { name: 'Kuwait', value: 'KW', label: 'کویت' },
  { name: 'Kyrgyzstan', value: 'KG', label: 'قرقیزستان' },
  { name: "Lao People'S Democratic Republic", value: 'LA', label: ' لائوس' },
  { name: 'Latvia', value: 'LV', label: 'لاتویا' },
  { name: 'Lebanon', value: 'LB', label: 'لبنان' },
  { name: 'Lesotho', value: 'LS', label: 'لسوتو' },
  { name: 'Liberia', value: 'LR', label: 'لیبریا' },
  { name: 'Libyan Arab Jamahiriya', value: 'LY', label: 'لیبی' },
  { name: 'Liechtenstein', value: 'LI', label: 'لیختنشتاین' },
  { name: 'Lithuania', value: 'LT', label: 'لیتوانی' },
  { name: 'Luxembourg', value: 'LU', label: 'لوگزامبورگ' },
  { name: 'Macao', value: 'MO', label: 'ماکائو' },
  { name: 'Macedonia, The Former Yugoslav Republic of', value: 'MK', label: 'مقدونیه' },
  { name: 'Madagascar', value: 'MG', label: 'ماداگاسکار' },
  { name: 'Malawi', value: 'MW', label: 'مالاوی' },
  { name: 'Malaysia', value: 'MY', label: 'مالزی' },
  { name: 'Maldives', value: 'MV', label: 'مالدیو' },
  { name: 'Mali', value: 'ML', label: 'مالی' },
  { name: 'Malta', value: 'MT', label: 'مالت' },
  { name: 'Marshall Islands', value: 'MH', label: 'جزایر مارشال' },
  { name: 'Mauritania', value: 'MR', label: 'موریتانی' },
  { name: 'Mauritius', value: 'MU', label: 'موریس' },
  { name: 'Mexico', value: 'MX', label: 'مکزیک' },
  { name: 'Micronesia, Federated States of', value: 'FM', label: 'میکرونزی' },
  { name: 'Moldova, Republic of', value: 'MD', label: 'مولداوی' },
  { name: 'Monaco', value: 'MC', label: 'موناکو' },
  { name: 'Mongolia', value: 'MN', label: 'مغولستان' },
  { name: 'Montenegro', value: 'ME', label: 'مونتنگرو' },
  { name: 'Morocco', value: 'MA', label: 'مراکش' },
  { name: 'Mozambique', value: 'MZ', label: 'موزامبیک' },
  { name: 'Myanmar', value: 'MM', label: 'میانمار' },
  { name: 'Namibia', value: 'NA', label: 'نامیبیا' },
  { name: 'Nauru', value: 'NR', label: 'نائورو' },
  { name: 'Nepal', value: 'NP', label: 'نپال' },
  { name: 'Netherlands', value: 'NL', label: 'هلند' },
  { name: 'Netherlands Antilles', value: 'AN', label: 'آنتیل هلند' },
  { name: 'New Zealand', value: 'NZ', label: 'نیوزیلند' },
  { name: 'Nicaragua', value: 'NI', label: 'نیکاراگوئه' },
  { name: 'Niger', value: 'NE', label: 'نیجر' },
  { name: 'Nigeria', value: 'NG', label: 'نیجریه' },
  { name: 'Northern Mariana Islands', value: 'MP', label: 'جزایر ماریان شمالی' },
  { name: 'Norway', value: 'NO', label: 'نروژ' },
  { name: 'Oman', value: 'OM', label: 'عمان' },
  { name: 'Pakistan', value: 'PK', label: 'پاکستان' },
  { name: 'Palau', value: 'PW', label: 'پالائو' },
  { name: 'Palestinian Territory, Occupied', value: 'PS', label: 'فلسطین' },
  { name: 'Panama', value: 'PA', label: 'پاناما' },
  { name: 'Papua New Guinea', value: 'PG', label: 'پاپوا گینه نو' },
  { name: 'Paraguay', value: 'PY', label: 'پاراگوئه' },
  { name: 'Peru', value: 'PE', label: 'پرو' },
  { name: 'Philippines', value: 'PH', label: 'فیلیپین' },
  { name: 'Poland', value: 'PL', label: 'لهستان' },
  { name: 'Portugal', value: 'PT', label: 'پرتغال' },
  { name: 'Puerto Rico', value: 'PR', label: 'پورتو ریکو' },
  { name: 'Qatar', value: 'QA', label: 'قطر' },
  { name: 'Romania', value: 'RO', label: 'رومانی' },
  { name: 'Russian Federation', value: 'RU', label: 'روسیه' },
  { name: 'RWANDA', value: 'RW', label: 'رواندا' },
  { name: 'Saint Kitts and Nevis', value: 'KN', label: 'سنت کیتس و نویس' },
  { name: 'Samoa', value: 'WS', label: 'ساموآ' },
  { name: 'San Marino', value: 'SM', label: 'سن مارینو' },
  { name: 'Saudi Arabia', value: 'SA', label: 'عربستان' },
  { name: 'Senegal', value: 'SN', label: 'سنگال' },
  { name: 'Serbia', value: 'RS', label: 'صربستان' },
  { name: 'Seychelles', value: 'SC', label: 'سیشل' },
  { name: 'Sierra Leone', value: 'SL', label: 'سیرالئون' },
  { name: 'Singapore', value: 'SG', label: 'سنگاپور' },
  { name: 'Slovakia', value: 'SK', label: 'اسلوواکی' },
  { name: 'Slovenia', value: 'SI', label: 'اسلوونی' },
  { name: 'Solomon Islands', value: 'SB', label: 'جزایر سلیمان' },
  { name: 'Somalia', value: 'SO', label: 'سومالی' },
  { name: 'South Africa', value: 'ZA', label: 'آفریقای جنوبی' },
  { name: 'Spain', value: 'ES', label: 'اسپانیا' },
  { name: 'Sri Lanka', value: 'LK', label: 'سریلانکا' },
  { name: 'Sudan', value: 'SD', label: 'سودان' },
  { name: 'Suriname', value: 'SR', label: 'سورینام' },
  { name: 'Swaziland', value: 'SZ', label: 'سوازیلند' },
  { name: 'Sweden', value: 'SE', label: 'سوئد' },
  { name: 'Switzerland', value: 'CH', label: 'سوییس' },
  { name: 'Syrian Arab Republic', value: 'SY', label: 'سوریه' },
  { name: 'Taiwan, Province of China', value: 'TW', label: 'تایوان' },
  { name: 'Tajikistan', value: 'TJ', label: 'تاجیکستان' },
  { name: 'Tanzania, United Republic of', value: 'TZ', label: 'تانزانیا' },
  { name: 'Thailand', value: 'TH', label: 'تایلند' },
  { name: 'Timor-Leste', value: 'TL', label: 'تیمور شرقی' },
  { name: 'Togo', value: 'TG', label: 'توگو' },
  { name: 'Tonga', value: 'TO', label: 'تونگا' },
  { name: 'Trinidad and Tobago', value: 'TT', label: 'ترینیداد' },
  { name: 'Tunisia', value: 'TN', label: 'تونس' },
  { name: 'Turkey', value: 'TR', label: 'ترکیه' },
  { name: 'Turkmenistan', value: 'TM', label: 'ترکمنستان' },
  { name: 'Tuvalu', value: 'TV', label: 'تووالو' },
  { name: 'Uganda', value: 'UG', label: 'اوگاندا' },
  { name: 'Ukraine', value: 'UA', label: 'اوکراین' },
  { name: 'United Arab Emirates', value: 'AE', label: 'امارات متحده' },
  { name: 'United Kingdom', value: 'GB', label: 'انگلیس' },
  { name: 'United States', value: 'US', label: 'آمریکا' },
  { name: 'Uruguay', value: 'UY', label: 'اروگوئه' },
  { name: 'Uzbekistan', value: 'UZ', label: 'ازبسکتان' },
  { name: 'Vanuatu', value: 'VU', label: 'وانواتو' },
  { name: 'Venezuela', value: 'VE', label: 'ونزوئلا' },
  { name: 'Viet Nam', value: 'VN', label: 'ویتنام' },
  { name: 'Western Sahara', value: 'EH', label: 'صحرای غربی' },
  { name: 'Yemen', value: 'YE', label: 'یمن' },
  { name: 'Zambia', value: 'ZM', label: 'زامبیا' },
  { name: 'Zimbabw', value: 'Z', label: 'زیمباوه' },
]
